import { fireEvent, render, screen } from '@testing-library/react';
import { describe, expect, it, vi } from 'vitest';
import LiveNowScreen, { acceptSpectatorSnapshot } from './LiveNowScreen.tsx';
import type { SpectatorPublicSnapshot, SpectatorSessionSummary } from '@racehorse/match-protocol';
const summary:SpectatorSessionSummary={sessionId:'live:1',kind:'multiplayer_match',status:'active',sequence:1,participants:[{userId:'u1',displayName:'Alice',avatarUrl:null,score:10,handCount:5},{userId:'u2',displayName:'Bob',avatarUrl:null,score:5,handCount:6}],handNumber:2,spectatorCount:3,startedAt:'2026-01-01T00:00:00.000Z',updatedAt:'2026-01-01T00:01:00.000Z',completedAt:null};
const snapshot:SpectatorPublicSnapshot={schemaVersion:1,...summary,board:null,activeParticipantIndex:0,consecutivePasses:0,boneyardCount:8,publicMoveFeed:[{id:'m1',sequence:1,timestamp:summary.updatedAt,participantName:'Alice',kind:'played',tile:{low:4,high:6},position:'left',message:'Alice played 4-6 on the left end'}],result:null};
type SocketHandler = (...args: unknown[]) => void;
function fakeSocket(){const handlers=new Map<string,SocketHandler>();return{on:vi.fn((event:string,handler:SocketHandler)=>{handlers.set(event,handler);}),off:vi.fn(),emit:vi.fn((event:string,_payload:unknown,ack?:SocketHandler)=>{if(event==='spectator:list')ack?.({ok:true,sessions:[summary]});if(event==='spectator:join')ack?.({ok:true,snapshot});}),handlers};}
describe('LiveNowScreen',()=>{it('renders discovery categories and opens one read-only viewer',async()=>{const socket=fakeSocket();render(<LiveNowScreen socket={socket as never} connect={vi.fn()} onBack={vi.fn()}/>);expect(await screen.findByText('Alice vs Bob')).toBeInTheDocument();expect(screen.getByRole('tab',{name:'Matches'})).toHaveAttribute('aria-selected','true');fireEvent.click(screen.getByRole('button',{name:/watch alice versus bob/i}));expect(await screen.findByLabelText('Alice, score 10, 5 tiles')).toBeInTheDocument();expect(screen.getByText('Alice played 4-6 on the left end')).toBeInTheDocument();expect(screen.queryByRole('button',{name:/draw|pass|play tile/i})).not.toBeInTheDocument();});it('shows intentional empty Daily Fritz state',async()=>{const socket=fakeSocket();render(<LiveNowScreen socket={socket as never} connect={vi.fn()} onBack={vi.fn()}/>);await screen.findByText('Alice vs Bob');fireEvent.click(screen.getByRole('tab',{name:'Daily Fritz'}));expect(screen.getByText('No Daily Fritz players are broadcasting right now.')).toBeInTheDocument();});it('rejects stale and cross-session snapshots',()=>{expect(acceptSpectatorSnapshot(snapshot,{...snapshot,sequence:0})).toBe(snapshot);expect(acceptSpectatorSnapshot(snapshot,{...snapshot,sessionId:'other',sequence:2})).toBe(snapshot);expect(acceptSpectatorSnapshot(snapshot,{...snapshot,sequence:2})).toMatchObject({sequence:2});});});
