const GUEST_ID_PATTERN = /^guest_[A-Za-z0-9_-]{8,96}$/;

/**
 * Guest identities are continuity hints, not authenticated account identities.
 * Accept only the namespace generated by the client and keep the value bounded
 * before it is used for an unranked room or matchmaking seat.
 */
export function normalizeUntrustedGuestId(value: unknown): string | null {
  if (typeof value !== 'string') return null;
  const normalized = value.trim();
  return GUEST_ID_PATTERN.test(normalized) ? normalized : null;
}

