import { useMemo } from 'react';
import type { UseAppRoutesPropsSource } from './useAppRoutesProps';

export type UseAppRoutesInputSource = UseAppRoutesPropsSource;

export function useAppRoutesInput(source: UseAppRoutesInputSource): UseAppRoutesPropsSource {
  return useMemo(
    (): UseAppRoutesPropsSource => ({
      host: source.host,
      routeBundles: source.routeBundles,
      friendInvitePopup: source.friendInvitePopup,
      multiplayerConnectionState: source.multiplayerConnectionState,
      multiplayerConnectionConfig: source.multiplayerConnectionConfig,
      connect: source.connect,
      retryRoomRecovery: source.retryRoomRecovery,
      isRecoveringConnection: source.isRecoveringConnection,
      serverWaking: source.serverWaking,
      roomRecoveryMessage: source.roomRecoveryMessage,
      actionError: source.actionError,
      state: source.state,
      startGame: source.startGame,
      setActionError: source.setActionError,
      overlayPayload: source.overlayPayload,
      setOverlayPayload: source.setOverlayPayload,
      handleMatchmakingAutoJoin: source.handleMatchmakingAutoJoin,
      isRoomHost: source.isRoomHost,
      privateLobbyHostWinStreak: source.privateLobbyHostWinStreak,
      you: source.you,
      players: source.players,
      pendingUiAction: source.pendingUiAction,
      opponentId: source.opponentId,
      opponentName: source.opponentName,
      myName: source.myName,
      myScore: source.myScore,
      opponentScore: source.opponentScore,
      opponentTileCount: source.opponentTileCount,
      isMyTurn: source.isMyTurn,
      isHandActive: source.isHandActive,
      hudScorePulse: source.hudScorePulse,
      hudRightLabel: source.hudRightLabel,
      hudRightScore: source.hudRightScore,
      hudRightScorePulse: source.hudRightScorePulse,
      opponentPillRef: source.opponentPillRef,
      boneyardRef: source.boneyardRef,
      boneyardCount: source.boneyardCount,
      openEndsSum: source.openEndsSum,
      boardRef: source.boardRef,
      handAreaRef: source.handAreaRef,
      trayCenterRef: source.trayCenterRef,
      confettiCanvasRef: source.confettiCanvasRef,
      boardForDisplay: source.boardForDisplay,
      boardLegalMoves: source.boardLegalMoves,
      boardSelectedTile: source.boardSelectedTile,
      lastPlayedTile: source.lastPlayedTile,
      boardShowOpenEndGlow: source.boardShowOpenEndGlow,
      play: source.play,
      myHand: source.myHand,
      handSelectedTile: source.handSelectedTile,
      handleTileTap: source.handleTileTap,
      legalMoves: source.legalMoves,
      handTileSize: source.handTileSize,
      handCompactStacked: source.handCompactStacked,
      drawPulseIndex: source.drawPulseIndex,
      scoreToast: source.scoreToast,
      scoreTrackOpen: source.scoreTrackOpen,
      setScoreTrackOpen: source.setScoreTrackOpen,
      isMuted: source.isMuted,
      setIsMuted: source.setIsMuted,
      isFullscreen: source.isFullscreen,
      toggleFullscreen: source.toggleFullscreen,
      opponentDisconnected: source.opponentDisconnected,
      opponentDisconnectMessage: source.opponentDisconnectMessage,
      handReveal: source.handReveal,
      handRevealAutoProgress: source.handRevealAutoProgress,
      flyingTiles: source.flyingTiles,
      canUseRematch: source.canUseRematch,
      rematchRequested: source.rematchRequested,
      rematchWaitingText: source.rematchWaitingText,
      requestRematch: source.requestRematch,
      handlePostGame: source.handlePostGame,
      multiplayerRatingSummary: source.multiplayerRatingSummary,
      openMultiplayerAnalyzer: source.openMultiplayerAnalyzer,
      showLeaveConfirm: source.showLeaveConfirm,
      setShowLeaveConfirm: source.setShowLeaveConfirm,
      abandonCurrentMatch: source.abandonCurrentMatch,
      abandonedMatchNotice: source.abandonedMatchNotice,
      setAbandonedMatchNotice: source.setAbandonedMatchNotice,
      recoveredPrivateMatch: source.recoveredPrivateMatch,
      setRecoveredPrivateMatch: source.setRecoveredPrivateMatch,
      tournamentMatch: source.tournamentMatch,
      consumedTournamentGameOverMatchIds: source.consumedTournamentGameOverMatchIds,
      tournamentMyLabel: source.tournamentMyLabel,
      tournamentOpponentLabel: source.tournamentOpponentLabel,
      navigateAfterTournamentMatch: source.navigateAfterTournamentMatch,
      currentTournamentContext: source.currentTournamentContext,
      preGameDraw: source.preGameDraw,
      onPregameTileTap: source.onPregameTileTap,
    }),
    [
      source.host,
      source.host.multiplayerConnectionHostParams,
      source.host.connectionActions,
      source.host.multiplayerLobbyHostProps,
      source.host.authModalsLayer,
      source.routeBundles,
      source.routeBundles.navigation,
      source.routeBundles.auth,
      source.routeBundles.learn,
      source.routeBundles.botMatch,
      source.routeBundles.ghost,
      source.routeBundles.social,
      source.routeBundles.homeOverlays,
      source.routeBundles.tournament,
      source.routeBundles.multiplayerRoute,
      source.friendInvitePopup,
      source.multiplayerConnectionState,
      source.multiplayerConnectionConfig,
      source.connect,
      source.retryRoomRecovery,
      source.isRecoveringConnection,
      source.serverWaking,
      source.roomRecoveryMessage,
      source.actionError,
      source.state,
      source.startGame,
      source.setActionError,
      source.overlayPayload,
      source.setOverlayPayload,
      source.handleMatchmakingAutoJoin,
      source.isRoomHost,
      source.privateLobbyHostWinStreak,
      source.you,
      source.players,
      source.pendingUiAction,
      source.opponentId,
      source.opponentName,
      source.myName,
      source.myScore,
      source.opponentScore,
      source.opponentTileCount,
      source.isMyTurn,
      source.isHandActive,
      source.hudScorePulse,
      source.hudRightLabel,
      source.hudRightScore,
      source.hudRightScorePulse,
      source.opponentPillRef,
      source.boneyardRef,
      source.boneyardCount,
      source.openEndsSum,
      source.boardRef,
      source.handAreaRef,
      source.trayCenterRef,
      source.confettiCanvasRef,
      source.boardForDisplay,
      source.boardLegalMoves,
      source.boardSelectedTile,
      source.lastPlayedTile,
      source.boardShowOpenEndGlow,
      source.play,
      source.myHand,
      source.handSelectedTile,
      source.handleTileTap,
      source.legalMoves,
      source.handTileSize,
      source.handCompactStacked,
      source.drawPulseIndex,
      source.scoreToast,
      source.scoreTrackOpen,
      source.setScoreTrackOpen,
      source.isMuted,
      source.setIsMuted,
      source.isFullscreen,
      source.toggleFullscreen,
      source.opponentDisconnected,
      source.opponentDisconnectMessage,
      source.handReveal,
      source.handRevealAutoProgress,
      source.flyingTiles,
      source.canUseRematch,
      source.rematchRequested,
      source.rematchWaitingText,
      source.requestRematch,
      source.handlePostGame,
      source.multiplayerRatingSummary,
      source.openMultiplayerAnalyzer,
      source.showLeaveConfirm,
      source.setShowLeaveConfirm,
      source.abandonCurrentMatch,
      source.abandonedMatchNotice,
      source.setAbandonedMatchNotice,
      source.recoveredPrivateMatch,
      source.setRecoveredPrivateMatch,
      source.tournamentMatch,
      source.consumedTournamentGameOverMatchIds,
      source.tournamentMyLabel,
      source.tournamentOpponentLabel,
      source.navigateAfterTournamentMatch,
      source.currentTournamentContext,
      source.preGameDraw,
      source.onPregameTileTap,
    ],
  );
}