import { useMemo } from 'react';
import type { UseAppRoutesPropsSource } from './useAppRoutesProps';

export type UseAppRoutesInputSource = UseAppRoutesPropsSource;

export function useAppRoutesInput(source: UseAppRoutesInputSource): UseAppRoutesPropsSource {
  return useMemo(
    (): UseAppRoutesPropsSource => ({
      host: source.host,
      multiplayerConnectionState: source.multiplayerConnectionState,
      multiplayerConnectionConfig: source.multiplayerConnectionConfig,
      connect: source.connect,
      retryRoomRecovery: source.retryRoomRecovery,
      isRecoveringConnection: source.isRecoveringConnection,
      serverWaking: source.serverWaking,
      roomRecoveryMessage: source.roomRecoveryMessage,
      setAppMode: source.setAppMode,
      overlayPayload: source.overlayPayload,
      setOverlayPayload: source.setOverlayPayload,
      handleMatchmakingAutoJoin: source.handleMatchmakingAutoJoin,
      isRoomHost: source.isRoomHost,
      privateLobbyHostWinStreak: source.privateLobbyHostWinStreak,
      you: source.you,
      players: source.players,
      pendingUiAction: source.pendingUiAction,
      opponentId: source.opponentId,
      opponentName: source.opponentName,
      myName: source.myName,
      myScore: source.myScore,
      opponentScore: source.opponentScore,
      opponentTileCount: source.opponentTileCount,
      isMyTurn: source.isMyTurn,
      isHandActive: source.isHandActive,
      hudScorePulse: source.hudScorePulse,
      hudRightLabel: source.hudRightLabel,
      hudRightScore: source.hudRightScore,
      hudRightScorePulse: source.hudRightScorePulse,
      opponentPillRef: source.opponentPillRef,
      boneyardRef: source.boneyardRef,
      boneyardCount: source.boneyardCount,
      openEndsSum: source.openEndsSum,
      boardRef: source.boardRef,
      handAreaRef: source.handAreaRef,
      trayCenterRef: source.trayCenterRef,
      confettiCanvasRef: source.confettiCanvasRef,
      boardForDisplay: source.boardForDisplay,
      boardLegalMoves: source.boardLegalMoves,
      boardSelectedTile: source.boardSelectedTile,
      lastPlayedTile: source.lastPlayedTile,
      boardShowOpenEndGlow: source.boardShowOpenEndGlow,
      play: source.play,
      myHand: source.myHand,
      handSelectedTile: source.handSelectedTile,
      handleTileTap: source.handleTileTap,
      legalMoves: source.legalMoves,
      handTileSize: source.handTileSize,
      handCompactStacked: source.handCompactStacked,
      drawPulseIndex: source.drawPulseIndex,
      scoreToast: source.scoreToast,
      scoreTrackOpen: source.scoreTrackOpen,
      setScoreTrackOpen: source.setScoreTrackOpen,
      isMuted: source.isMuted,
      setIsMuted: source.setIsMuted,
      isFullscreen: source.isFullscreen,
      toggleFullscreen: source.toggleFullscreen,
      opponentDisconnected: source.opponentDisconnected,
      opponentDisconnectMessage: source.opponentDisconnectMessage,
      handReveal: source.handReveal,
      handRevealAutoProgress: source.handRevealAutoProgress,
      flyingTiles: source.flyingTiles,
      canUseRematch: source.canUseRematch,
      rematchRequested: source.rematchRequested,
      rematchWaitingText: source.rematchWaitingText,
      requestRematch: source.requestRematch,
      handlePostGame: source.handlePostGame,
      multiplayerRatingSummary: source.multiplayerRatingSummary,
      openMultiplayerAnalyzer: source.openMultiplayerAnalyzer,
      showLeaveConfirm: source.showLeaveConfirm,
      setShowLeaveConfirm: source.setShowLeaveConfirm,
      abandonCurrentMatch: source.abandonCurrentMatch,
      abandonedMatchNotice: source.abandonedMatchNotice,
      setAbandonedMatchNotice: source.setAbandonedMatchNotice,
      tournamentMatch: source.tournamentMatch,
      consumedTournamentGameOverMatchIdsRef: source.consumedTournamentGameOverMatchIdsRef,
      tournamentMyLabel: source.tournamentMyLabel,
      tournamentOpponentLabel: source.tournamentOpponentLabel,
      navigateAfterTournamentMatch: source.navigateAfterTournamentMatch,
      currentTournamentContext: source.currentTournamentContext,
      appMode: source.appMode,
      appRootRef: source.appRootRef,
      canOpenHowToPlayPreview: source.canOpenHowToPlayPreview,
      isAdmin: source.isAdmin,
      authUser: source.authUser,
      authProfile: source.authProfile,
      supabaseEnabled: source.supabaseEnabled,
      supabaseConfigError: source.supabaseConfigError,
      selectedLearnLessonId: source.selectedLearnLessonId,
      setSelectedLearnLessonId: source.setSelectedLearnLessonId,
      learnHowToPlayOpen: source.learnHowToPlayOpen,
      setLearnHowToPlayOpen: source.setLearnHowToPlayOpen,
      setIsGuidedMode: source.setIsGuidedMode,
      setIsAuthoringMode: source.setIsAuthoringMode,
      setIsAuthoringV2Mode: source.setIsAuthoringV2Mode,
      setIsGuidedV2Mode: source.setIsGuidedV2Mode,
      setBotFritzTier: source.setBotFritzTier,
      setBotDealSize: source.setBotDealSize,
      botDealSize: source.botDealSize,
      botFritzTier: source.botFritzTier,
      isGuidedMode: source.isGuidedMode,
      isAuthoringMode: source.isAuthoringMode,
      isAuthoringV2Mode: source.isAuthoringV2Mode,
      isGuidedV2Mode: source.isGuidedV2Mode,
      refreshAuthProfile: source.refreshAuthProfile,
      applyProfilePatch: source.applyProfilePatch,
      ghostProfile: source.ghostProfile,
      setGhostProfile: source.setGhostProfile,
      ghostOpponentName: source.ghostOpponentName,
      ghostOpponentUserId: source.ghostOpponentUserId,
      setGhostOpponentName: source.setGhostOpponentName,
      setGhostOpponentUserId: source.setGhostOpponentUserId,
      setAuthModalOpen: source.setAuthModalOpen,
      setUsernameModalOpen: source.setUsernameModalOpen,
      socket: source.socket,
      joinedRoom: source.joinedRoom,
      showToast: source.showToast,
      outboundChallenge: source.outboundChallenge,
      clearOutboundChallenge: source.clearOutboundChallenge,
      profileTarget: source.profileTarget,
      setProfileTarget: source.setProfileTarget,
      friendInvitePopup: source.friendInvitePopup,
      toast: source.toast,
      error: source.error,
      actionError: source.actionError,
      state: source.state,
      setError: source.setError,
      setActionError: source.setActionError,
      mpSubView: source.mpSubView,
      startGame: source.startGame,
      myHandle: source.myHandle,
      homeRatingLabel: source.homeRatingLabel,
      activeHomeMode: source.activeHomeMode,
      setActiveHomeMode: source.setActiveHomeMode,
      welcomeOpen: source.welcomeOpen,
      setWelcomeOpen: source.setWelcomeOpen,
      weeklyStatsOpen: source.weeklyStatsOpen,
      setWeeklyStatsOpen: source.setWeeklyStatsOpen,
      tournament: source.tournament,
      tournamentSubView: source.tournamentSubView,
      activeTournamentId: source.activeTournamentId,
      tournamentAttachPhase: source.tournamentAttachPhase,
      tournamentAttachError: source.tournamentAttachError,
      tournamentResult: source.tournamentResult,
      tournamentResultLoading: source.tournamentResultLoading,
      tournamentResultError: source.tournamentResultError,
      setTournamentSubView: source.setTournamentSubView,
      setActiveTournamentId: source.setActiveTournamentId,
      setTournamentResult: source.setTournamentResult,
      setTournamentResultLoading: source.setTournamentResultLoading,
      setTournamentResultError: source.setTournamentResultError,
      exitToTournamentHub: source.exitToTournamentHub,
      enterTournamentLobby: source.enterTournamentLobby,
      attachAssignedTournamentMatch: source.attachAssignedTournamentMatch,
    }),
    [
      source.host.multiplayerConnectionHostParams,
      source.host.connectionActions,
      source.host.multiplayerLobbyHostProps,
      source.host.authModalsLayer,
      source.multiplayerConnectionState,
      source.multiplayerConnectionConfig,
      source.connect,
      source.retryRoomRecovery,
      source.isRecoveringConnection,
      source.serverWaking,
      source.roomRecoveryMessage,
      source.setAppMode,
      source.overlayPayload,
      source.setOverlayPayload,
      source.handleMatchmakingAutoJoin,
      source.isRoomHost,
      source.privateLobbyHostWinStreak,
      source.you,
      source.players,
      source.pendingUiAction,
      source.opponentId,
      source.opponentName,
      source.myName,
      source.myScore,
      source.opponentScore,
      source.opponentTileCount,
      source.isMyTurn,
      source.isHandActive,
      source.hudScorePulse,
      source.hudRightLabel,
      source.hudRightScore,
      source.hudRightScorePulse,
      source.opponentPillRef,
      source.boneyardRef,
      source.boneyardCount,
      source.openEndsSum,
      source.boardRef,
      source.handAreaRef,
      source.trayCenterRef,
      source.confettiCanvasRef,
      source.boardForDisplay,
      source.boardLegalMoves,
      source.boardSelectedTile,
      source.lastPlayedTile,
      source.boardShowOpenEndGlow,
      source.play,
      source.myHand,
      source.handSelectedTile,
      source.handleTileTap,
      source.legalMoves,
      source.handTileSize,
      source.handCompactStacked,
      source.drawPulseIndex,
      source.scoreToast,
      source.scoreTrackOpen,
      source.setScoreTrackOpen,
      source.isMuted,
      source.setIsMuted,
      source.isFullscreen,
      source.toggleFullscreen,
      source.opponentDisconnected,
      source.opponentDisconnectMessage,
      source.handReveal,
      source.handRevealAutoProgress,
      source.flyingTiles,
      source.canUseRematch,
      source.rematchRequested,
      source.rematchWaitingText,
      source.requestRematch,
      source.handlePostGame,
      source.multiplayerRatingSummary,
      source.openMultiplayerAnalyzer,
      source.showLeaveConfirm,
      source.setShowLeaveConfirm,
      source.abandonCurrentMatch,
      source.abandonedMatchNotice,
      source.setAbandonedMatchNotice,
      source.tournamentMatch,
      source.consumedTournamentGameOverMatchIdsRef,
      source.tournamentMyLabel,
      source.tournamentOpponentLabel,
      source.navigateAfterTournamentMatch,
      source.currentTournamentContext,
      source.appMode,
      source.appRootRef,
      source.canOpenHowToPlayPreview,
      source.isAdmin,
      source.authUser,
      source.authProfile,
      source.supabaseEnabled,
      source.supabaseConfigError,
      source.selectedLearnLessonId,
      source.setSelectedLearnLessonId,
      source.learnHowToPlayOpen,
      source.setLearnHowToPlayOpen,
      source.setIsGuidedMode,
      source.setIsAuthoringMode,
      source.setIsAuthoringV2Mode,
      source.setIsGuidedV2Mode,
      source.setBotFritzTier,
      source.setBotDealSize,
      source.botDealSize,
      source.botFritzTier,
      source.isGuidedMode,
      source.isAuthoringMode,
      source.isAuthoringV2Mode,
      source.isGuidedV2Mode,
      source.refreshAuthProfile,
      source.applyProfilePatch,
      source.ghostProfile,
      source.setGhostProfile,
      source.ghostOpponentName,
      source.ghostOpponentUserId,
      source.setGhostOpponentName,
      source.setGhostOpponentUserId,
      source.setAuthModalOpen,
      source.setUsernameModalOpen,
      source.socket,
      source.joinedRoom,
      source.showToast,
      source.outboundChallenge,
      source.clearOutboundChallenge,
      source.profileTarget,
      source.setProfileTarget,
      source.friendInvitePopup,
      source.toast,
      source.error,
      source.actionError,
      source.state,
      source.setError,
      source.setActionError,
      source.mpSubView,
      source.startGame,
      source.myHandle,
      source.homeRatingLabel,
      source.activeHomeMode,
      source.setActiveHomeMode,
      source.welcomeOpen,
      source.setWelcomeOpen,
      source.weeklyStatsOpen,
      source.setWeeklyStatsOpen,
      source.tournament,
      source.tournamentSubView,
      source.activeTournamentId,
      source.tournamentAttachPhase,
      source.tournamentAttachError,
      source.tournamentResult,
      source.tournamentResultLoading,
      source.tournamentResultError,
      source.setTournamentSubView,
      source.setActiveTournamentId,
      source.setTournamentResult,
      source.setTournamentResultLoading,
      source.setTournamentResultError,
      source.exitToTournamentHub,
      source.enterTournamentLobby,
      source.attachAssignedTournamentMatch,
    ],
  );
}
