import type { Server, Socket } from 'socket.io';
import { randomUUID } from 'crypto';
import type { Room } from '../rooms';
const SPECTATOR_DISCOVERY_LIMIT = 50;
const SPECTATOR_MOVE_FEED_LIMIT = 30;
type SpectatorParticipant = { userId: string | null; displayName: string; avatarUrl: string | null; score: number; handCount: number; connectionStatus?: 'connected' | 'reconnecting' | 'disconnected' };
type SpectatorPublicSnapshot = { schemaVersion: 1; sessionId: string; kind: 'multiplayer_match' | 'daily_fritz'; sequence: number; status: 'waiting' | 'active' | 'paused' | 'completed' | 'ended'; board: unknown; participants: SpectatorParticipant[]; activeParticipantIndex: number | null; consecutivePasses: number; boneyardCount: number; handNumber: number; publicMoveFeed: Array<Record<string, unknown>>; spectatorCount: number; startedAt: string; updatedAt: string; completedAt: string | null; result: { winnerDisplayName: string | null; finalScores: number[]; reason: string } | null };
type SpectatorSessionSummary = Pick<SpectatorPublicSnapshot, 'sessionId'|'kind'|'status'|'sequence'|'participants'|'handNumber'|'spectatorCount'|'startedAt'|'updatedAt'|'completedAt'>;
const isObject = (value: unknown): value is Record<string, unknown> => Boolean(value) && typeof value === 'object' && !Array.isArray(value);
const isSpectatorListRequest = (value: unknown): value is {kind?:'all'|'multiplayer_match'|'daily_fritz';limit?:number} => isObject(value) && (value.kind === undefined || ['all','multiplayer_match','daily_fritz'].includes(String(value.kind))) && (value.limit === undefined || Number.isInteger(value.limit) && Number(value.limit) > 0 && Number(value.limit) <= SPECTATOR_DISCOVERY_LIMIT);
const isSpectatorJoinRequest = (value: unknown): value is {sessionId:string} => isObject(value) && typeof value.sessionId === 'string' && value.sessionId.length > 0;
const isSpectatorPublicSnapshot = (value: unknown): value is SpectatorPublicSnapshot => isObject(value) && value.schemaVersion === 1 && typeof value.sessionId === 'string' && ['multiplayer_match','daily_fritz'].includes(String(value.kind)) && Number.isInteger(value.sequence) && Array.isArray(value.participants) && Array.isArray(value.publicMoveFeed) && value.publicMoveFeed.length <= SPECTATOR_MOVE_FEED_LIMIT;
const FORBIDDEN_PUBLIC_KEYS = new Set(['hand','boneyard','socketId','authToken','recoveryToken','inviteCode','verificationToken','randomSeed','plannedMove','opponentKnownMissing']);
function assertNoPrivateKeys(value: unknown): void { if (Array.isArray(value)) { value.forEach(assertNoPrivateKeys); return; } if (!isObject(value)) return; for (const [key,nested] of Object.entries(value)) { if (FORBIDDEN_PUBLIC_KEYS.has(key)) throw new Error(`forbidden spectator field ${key}`); assertNoPrivateKeys(nested); } }
function assertSpectatorSnapshotSafe(snapshot: SpectatorPublicSnapshot): void { if(!isSpectatorPublicSnapshot(snapshot)) throw new Error('malformed spectator snapshot'); assertNoPrivateKeys(snapshot); }

export const SPECTATOR_MAX_PER_SESSION = 100;
export const SPECTATOR_MAX_ACTIVE_SESSIONS = 200;
export const SPECTATOR_TERMINAL_RETENTION_MS = 5 * 60_000;
type ActiveSession = { sourceId: string; ownerSocketId: string | null; spectatorSocketIds: Set<string>; latestSnapshot: SpectatorPublicSnapshot; createdAt: number; updatedAt: number; terminalExpiresAt: number | null };
const sessions = new Map<string, ActiveSession>();
const multiplayerSessionByRoom = new Map<string, string>();

const summary = (session: ActiveSession): SpectatorSessionSummary => { const s = session.latestSnapshot; return { sessionId: s.sessionId, kind: s.kind, status: s.status, sequence: s.sequence, participants: s.participants, handNumber: s.handNumber, spectatorCount: session.spectatorSocketIds.size, startedAt: s.startedAt, updatedAt: s.updatedAt, completedAt: s.completedAt }; };
export function listSpectatorSessions(kind: 'all' | 'multiplayer_match' | 'daily_fritz' = 'all', limit = SPECTATOR_DISCOVERY_LIMIT): SpectatorSessionSummary[] { cleanupSpectatorSessions(); return [...sessions.values()].filter((s) => kind === 'all' || s.latestSnapshot.kind === kind).sort((a,b) => Number(b.latestSnapshot.status === 'active') - Number(a.latestSnapshot.status === 'active') || b.spectatorSocketIds.size - a.spectatorSocketIds.size || b.updatedAt - a.updatedAt).slice(0, Math.min(limit, SPECTATOR_DISCOVERY_LIMIT)).map(summary); }
export function getSpectatorSnapshot(sessionId: string): SpectatorPublicSnapshot | null { const session = sessions.get(sessionId); return session ? { ...session.latestSnapshot, spectatorCount: session.spectatorSocketIds.size } : null; }
export function cleanupSpectatorSessions(now = Date.now(), io?: Pick<Server, 'emit'>): void { for (const [id, session] of sessions) if (session.terminalExpiresAt != null && session.terminalExpiresAt <= now) { sessions.delete(id); if (session.latestSnapshot.kind === 'multiplayer_match') multiplayerSessionByRoom.delete(session.sourceId); io?.emit('spectator:session_removed', { sessionId: id }); } }
export function resetSpectatorRegistryForTests(): void { sessions.clear(); multiplayerSessionByRoom.clear(); }

type PublicRosterEntry = { id: string; username: string; userId: string | null };
function roomMoveFeed(room: Room, roster: PublicRosterEntry[]) { const names = new Map(roster.map((p) => [p.userId, p.username])); return room.events.filter((event) => ['tile_played','tile_drawn','turn_passed','hand_ended','match_ended'].includes(event.type)).slice(-SPECTATOR_MOVE_FEED_LIMIT).map((event) => { const tile = event.type === 'tile_played' && event.payload.tile && typeof event.payload.tile === 'object' ? event.payload.tile as { low: number; high: number } : undefined; const participantName = event.actorUserId ? names.get(event.actorUserId) ?? null : null; const actor = participantName ?? 'A player'; const message = event.type === 'tile_played' && tile ? `${actor} played ${tile.low}-${tile.high}` : event.type === 'tile_drawn' ? `${actor} drew a tile` : event.type === 'turn_passed' ? `${actor} passed` : event.type === 'hand_ended' ? 'The hand ended' : 'The match ended'; return { id: event.id, sequence: event.sequence, timestamp: event.timestamp, participantName, kind: event.type === 'tile_played' ? 'played' as const : event.type === 'tile_drawn' ? 'drew' as const : event.type === 'turn_passed' ? 'passed' as const : event.type === 'hand_ended' ? 'hand_ended' as const : 'completed' as const, ...(tile ? { tile } : {}), message }; }); }
export function projectMultiplayerRoomForSpectators(room: Room, roster: PublicRosterEntry[]): SpectatorPublicSnapshot | null { if (!room.state || !room.matchmakingMatchId || room.scheduledTournamentMatchId || room.abandonedAt) return null; const rosterBySeat = new Map(roster.map((p) => [p.id,p])); const now = new Date().toISOString(); const existingId = multiplayerSessionByRoom.get(room.code); const sessionId = existingId ?? `spectator:mp:${room.matchId}`; const participants = room.state.playerIds.map((seatId) => { const p = rosterBySeat.get(seatId); return { userId: p?.userId ?? null, displayName: p?.username ?? 'Player', avatarUrl: null, score: room.state!.players[seatId]?.score ?? 0, handCount: room.state!.players[seatId]?.hand.length ?? 0, connectionStatus: 'connected' as const }; }); const winner = room.state.winnerId; return { schemaVersion: 1, sessionId, kind: 'multiplayer_match', sequence: Math.max(room.state.sequence, room.eventSequence), status: room.state.gameOver ? 'completed' : 'active', board: room.state.board ? structuredClone(room.state.board) : null, participants, activeParticipantIndex: room.state.gameOver ? null : room.state.currentPlayerIndex, consecutivePasses: room.state.consecutivePasses, boneyardCount: room.state.boneyard.length, handNumber: room.state.handNumber, publicMoveFeed: roomMoveFeed(room, roster), spectatorCount: 0, startedAt: room.events.find((e) => e.type === 'match_started')?.timestamp ?? now, updatedAt: now, completedAt: room.state.gameOver ? now : null, result: room.state.gameOver ? { winnerDisplayName: winner ? rosterBySeat.get(winner)?.username ?? null : null, finalScores: participants.map((p) => p.score), reason: 'match_completed' } : null }; }
export function publishMultiplayerSpectatorSnapshot(io: Server, room: Room, roster: PublicRosterEntry[]): void { const snapshot = projectMultiplayerRoomForSpectators(room, roster); if (!snapshot) return; assertSpectatorSnapshotSafe(snapshot); let session = sessions.get(snapshot.sessionId); if (!session) { if (sessions.size >= SPECTATOR_MAX_ACTIVE_SESSIONS) cleanupSpectatorSessions(); if (sessions.size >= SPECTATOR_MAX_ACTIVE_SESSIONS) return; session = { sourceId: room.code, ownerSocketId: null, spectatorSocketIds: new Set(), latestSnapshot: snapshot, createdAt: Date.now(), updatedAt: Date.now(), terminalExpiresAt: null }; sessions.set(snapshot.sessionId, session); multiplayerSessionByRoom.set(room.code, snapshot.sessionId); io.emit('spectator:session_added', summary(session)); } else if (snapshot.sequence < session.latestSnapshot.sequence) return; session.latestSnapshot = { ...snapshot, spectatorCount: session.spectatorSocketIds.size }; session.updatedAt = Date.now(); session.terminalExpiresAt = snapshot.status === 'completed' ? Date.now() + SPECTATOR_TERMINAL_RETENTION_MS : null; io.to(`spectator:${snapshot.sessionId}`).emit('spectator:update', session.latestSnapshot); io.emit('spectator:session_updated', summary(session)); }

export function registerSpectatorHandlers(io: Server, socket: Socket): void {
  socket.on('spectator:list', (payload: unknown, cb?: (value: unknown) => void) => { if (!isSpectatorListRequest(payload)) return cb?.({ ok:false,error:'malformed_request' }); cleanupSpectatorSessions(Date.now(), io); cb?.({ ok:true, sessions:listSpectatorSessions(payload.kind ?? 'all', payload.limit ?? SPECTATOR_DISCOVERY_LIMIT) }); });
  socket.on('spectator:join', (payload: unknown, cb?: (value: unknown) => void) => { if (!isSpectatorJoinRequest(payload)) return cb?.({ ok:false,error:'malformed_request' }); const session = sessions.get(payload.sessionId); if (!session) return cb?.({ ok:false,error:'session_not_found' }); if (session.spectatorSocketIds.size >= SPECTATOR_MAX_PER_SESSION && !session.spectatorSocketIds.has(socket.id)) return cb?.({ ok:false,error:'spectator_limit_reached' }); const previous = typeof socket.data?.spectatorSessionId === 'string' ? socket.data.spectatorSessionId : null; if (previous && previous !== payload.sessionId) leaveSpectator(io,socket,previous); session.spectatorSocketIds.add(socket.id); socket.join(`spectator:${payload.sessionId}`); socket.data.spectatorSessionId = payload.sessionId; const snap = { ...session.latestSnapshot, spectatorCount:session.spectatorSocketIds.size }; session.latestSnapshot = snap; io.to(`spectator:${payload.sessionId}`).emit('spectator:count',{ sessionId:payload.sessionId,count:snap.spectatorCount }); cb?.({ ok:true,snapshot:snap }); });
  socket.on('spectator:leave', (payload: unknown, cb?: (value: unknown) => void) => { if (!isSpectatorJoinRequest(payload)) return cb?.({ok:false,error:'malformed_request'}); leaveSpectator(io,socket,payload.sessionId); cb?.({ok:true}); });
  socket.on('daily_fritz:broadcast_start', (payload: unknown, cb?: (value: unknown) => void) => { const owner = typeof socket.data?.userId === 'string' ? socket.data.userId : null; if (!owner) return cb?.({ok:false,error:'authentication_required'}); if (!payload || typeof payload !== 'object') return cb?.({ok:false,error:'malformed_broadcast'}); const p = payload as { runId?: string; snapshot?: SpectatorPublicSnapshot }; if (!p.runId || !p.snapshot || !isSpectatorPublicSnapshot(p.snapshot) || p.snapshot.participants.length !== 2) return cb?.({ok:false,error:'malformed_broadcast'}); cleanupSpectatorSessions(); if (sessions.size >= SPECTATOR_MAX_ACTIVE_SESSIONS) return cb?.({ok:false,error:'session_limit_reached'}); const prior = typeof socket.data?.dailyFritzBroadcastId === 'string' ? socket.data.dailyFritzBroadcastId : null; if (prior) endDailyBroadcast(io,prior,'broadcast_restarted'); const id = `spectator:daily:${owner}:${randomUUID()}`; const snap = { ...p.snapshot, sessionId:id, kind:'daily_fritz' as const, spectatorCount:0, participants:p.snapshot.participants.map((participant,index)=>({ ...participant,userId:index===0?owner:null })) }; assertSpectatorSnapshotSafe(snap); const session = { sourceId:p.runId,ownerSocketId:socket.id,spectatorSocketIds:new Set<string>(),latestSnapshot:snap,createdAt:Date.now(),updatedAt:Date.now(),terminalExpiresAt:null }; sessions.set(id,session); socket.data.dailyFritzBroadcastId=id; io.emit('spectator:session_added',summary(session)); cb?.({ok:true,sessionId:id,snapshot:snap}); });
  socket.on('daily_fritz:broadcast_update', (payload: unknown, cb?: (value: unknown) => void) => { const p = payload as { sessionId?:string;snapshot?:SpectatorPublicSnapshot }; const session = p?.sessionId ? sessions.get(p.sessionId) : null; if (!session || session.ownerSocketId !== socket.id) return cb?.({ok:false,error:'access_denied'}); if (!p.snapshot || !isSpectatorPublicSnapshot(p.snapshot) || p.snapshot.participants.length !== 2 || p.snapshot.sequence <= session.latestSnapshot.sequence) return cb?.({ok:false,error:'stale_or_malformed'}); const owner = session.latestSnapshot.participants[0]?.userId ?? null; const snap = { ...p.snapshot,sessionId:p.sessionId!,kind:'daily_fritz' as const,spectatorCount:session.spectatorSocketIds.size,participants:p.snapshot.participants.map((participant,index)=>({ ...participant,userId:index===0?owner:null })) }; assertSpectatorSnapshotSafe(snap); session.latestSnapshot=snap; session.updatedAt=Date.now(); io.to(`spectator:${p.sessionId}`).emit('spectator:update',snap); io.emit('spectator:session_updated',summary(session)); cb?.({ok:true}); });
  socket.on('daily_fritz:broadcast_stop', (payload: unknown, cb?: (value: unknown) => void) => { const id = (payload as {sessionId?:string})?.sessionId; const session = id ? sessions.get(id) : null; if (!session || session.ownerSocketId !== socket.id) return cb?.({ok:false,error:'access_denied'}); endDailyBroadcast(io,id!,'broadcast_stopped'); cb?.({ok:true}); });
  socket.on('disconnect', () => { const viewed = typeof socket.data?.spectatorSessionId === 'string' ? socket.data.spectatorSessionId : null; if (viewed) leaveSpectator(io,socket,viewed); const owned = typeof socket.data?.dailyFritzBroadcastId === 'string' ? socket.data.dailyFritzBroadcastId : null; if (owned) endDailyBroadcast(io,owned,'broadcaster_disconnected'); });
}
function leaveSpectator(io:Server,socket:Socket,id:string){ const session=sessions.get(id); if(!session)return; session.spectatorSocketIds.delete(socket.id); if(socket.data.spectatorSessionId===id) delete socket.data.spectatorSessionId; socket.leave(`spectator:${id}`); io.to(`spectator:${id}`).emit('spectator:count',{sessionId:id,count:session.spectatorSocketIds.size}); }
function endDailyBroadcast(io:Server,id:string,reason:string){ const session=sessions.get(id); if(!session)return; const now=new Date().toISOString(); session.latestSnapshot={...session.latestSnapshot,status:'ended',sequence:session.latestSnapshot.sequence+1,updatedAt:now,completedAt:now,result:{winnerDisplayName:null,finalScores:session.latestSnapshot.participants.map(p=>p.score),reason}}; session.terminalExpiresAt=Date.now()+SPECTATOR_TERMINAL_RETENTION_MS; io.to(`spectator:${id}`).emit('spectator:ended',session.latestSnapshot); io.emit('spectator:session_updated',summary(session)); }
