import { JOURNEY_CHAPTER_1_ID, type JourneyNode } from '../journeyTypes.ts';

export const CH1_FRITZ_TRAIL_CHAPTER_TITLE = 'Chapter 1: The Fritz Trail';

export const CH1_FRITZ_TRAIL_NODES: JourneyNode[] = [
  {
    id: 'ch1-n01',
    chapterId: JOURNEY_CHAPTER_1_ID,
    chapterTitle: CH1_FRITZ_TRAIL_CHAPTER_TITLE,
    order: 1,
    title: 'Trailhead Briefing',
    subtitle: 'Fritz welcomes you to the long road.',
    nodeType: 'checkpoint',
    difficulty: 'intro',
    requirements: ['Begin the Fritz Trail'],
    rewardText: 'Trail Marker',
    badgeText: 'START',
    action: { kind: 'placeholder' },
    completionCriteria: 'Complete the trailhead briefing.',
  },
  {
    id: 'ch1-n02',
    chapterId: JOURNEY_CHAPTER_1_ID,
    chapterTitle: CH1_FRITZ_TRAIL_CHAPTER_TITLE,
    order: 2,
    title: 'First Score',
    subtitle: 'Win your first short Racehorse push to 25.',
    nodeType: 'match',
    difficulty: 'casual',
    requirements: ['Complete Trailhead Briefing'],
    rewardText: 'First Blood',
    action: { kind: 'botMatch', fritzTier: 'rookie', dealSize: 7, trialFormat: 'shortRace', winningScore: 25 },
    completionCriteria: 'Win a short race to 25 vs Rookie Fritz.',
  },
  {
    id: 'ch1-n03',
    chapterId: JOURNEY_CHAPTER_1_ID,
    chapterTitle: CH1_FRITZ_TRAIL_CHAPTER_TITLE,
    order: 3,
    title: 'Open Ends Trial',
    subtitle: 'Read the board. Maximize open-end pressure.',
    nodeType: 'puzzle',
    difficulty: 'casual',
    requirements: ['Complete First Score'],
    rewardText: 'Open Eye',
    action: { kind: 'puzzle', puzzleId: 'ch1-open-ends' },
    completionCriteria: 'Solve the open-ends challenge puzzle.',
  },
  {
    id: 'ch1-n04',
    chapterId: JOURNEY_CHAPTER_1_ID,
    chapterTitle: CH1_FRITZ_TRAIL_CHAPTER_TITLE,
    order: 4,
    title: 'Draw Escape',
    subtitle: 'Survive the boneyard without panic.',
    nodeType: 'match',
    difficulty: 'casual',
    requirements: ['Complete Open Ends Trial'],
    rewardText: 'Steady Hand',
    action: { kind: 'botMatch', fritzTier: 'rookie', dealSize: 7, trialFormat: 'shortRace', winningScore: 30 },
    completionCriteria: 'Win a short race to 30 vs Rookie Fritz.',
  },
  {
    id: 'ch1-n05',
    chapterId: JOURNEY_CHAPTER_1_ID,
    chapterTitle: CH1_FRITZ_TRAIL_CHAPTER_TITLE,
    order: 5,
    title: 'Porch Fritz',
    subtitle: 'Standard Fritz on the porch—no excuses.',
    nodeType: 'match',
    difficulty: 'standard',
    requirements: ['Complete Draw Escape'],
    rewardText: 'Porch Pass',
    action: { kind: 'botMatch', fritzTier: 'standard', dealSize: 7, trialFormat: 'shortRace', winningScore: 35 },
    completionCriteria: 'Win a short race to 35 vs Standard Fritz.',
  },
  {
    id: 'ch1-n06',
    chapterId: JOURNEY_CHAPTER_1_ID,
    chapterTitle: CH1_FRITZ_TRAIL_CHAPTER_TITLE,
    order: 6,
    title: 'Tempo Test',
    subtitle: 'Keep initiative hand over hand.',
    nodeType: 'match',
    difficulty: 'standard',
    requirements: ['Complete Porch Fritz'],
    rewardText: 'Tempo',
    action: { kind: 'botMatch', fritzTier: 'standard', dealSize: 7, trialFormat: 'shortRace', winningScore: 35 },
    completionCriteria: 'Win a short race to 35 vs Standard Fritz with tempo pressure.',
  },
  {
    id: 'ch1-n07',
    chapterId: JOURNEY_CHAPTER_1_ID,
    chapterTitle: CH1_FRITZ_TRAIL_CHAPTER_TITLE,
    order: 7,
    title: 'Double Trouble',
    subtitle: 'Doubles decide tempo. Know when to feed and when to lock.',
    nodeType: 'checkpoint',
    difficulty: 'standard',
    requirements: ['Complete Tempo Test'],
    rewardText: 'Double Down',
    action: { kind: 'lesson', lessonId: 'doubles-tempo' },
    completionCriteria: 'Complete the doubles checkpoint.',
  },
  {
    id: 'ch1-n08',
    chapterId: JOURNEY_CHAPTER_1_ID,
    chapterTitle: CH1_FRITZ_TRAIL_CHAPTER_TITLE,
    order: 8,
    title: 'Puzzle Gate',
    subtitle: 'One board. One chance. Find the line.',
    nodeType: 'puzzle',
    difficulty: 'standard',
    requirements: ['Complete Double Trouble'],
    rewardText: 'Gate Cleared',
    action: { kind: 'puzzle', puzzleId: 'ch1-puzzle-gate' },
    completionCriteria: 'Solve the puzzle gate challenge.',
  },
  {
    id: 'ch1-n09',
    chapterId: JOURNEY_CHAPTER_1_ID,
    chapterTitle: CH1_FRITZ_TRAIL_CHAPTER_TITLE,
    order: 9,
    title: 'Pressure Hand',
    subtitle: 'Fixed hand under score pressure.',
    nodeType: 'puzzle',
    difficulty: 'hard',
    requirements: ['Complete Puzzle Gate'],
    rewardText: 'Ice Veins',
    action: { kind: 'puzzle', puzzleId: 'ch1-pressure-hand' },
    completionCriteria: 'Clear the pressure-hand challenge.',
  },
  {
    id: 'ch1-n10',
    chapterId: JOURNEY_CHAPTER_1_ID,
    chapterTitle: CH1_FRITZ_TRAIL_CHAPTER_TITLE,
    order: 10,
    title: 'Elite Warmup',
    subtitle: 'Elite Fritz—the Daily Fritz strength.',
    nodeType: 'match',
    difficulty: 'hard',
    requirements: ['Complete Pressure Hand'],
    rewardText: 'Elite Crest',
    action: { kind: 'botMatch', fritzTier: 'elite', dealSize: 7, trialFormat: 'shortRace', winningScore: 45 },
    completionCriteria: 'Win a short race to 45 vs Elite Fritz.',
  },
  {
    id: 'ch1-n11',
    chapterId: JOURNEY_CHAPTER_1_ID,
    chapterTitle: CH1_FRITZ_TRAIL_CHAPTER_TITLE,
    order: 11,
    title: 'No-Hint Trial',
    subtitle: 'Master Fritz with coaching stripped back.',
    nodeType: 'match',
    difficulty: 'expert',
    requirements: ['Complete Elite Warmup'],
    rewardText: 'Silent Focus',
    action: { kind: 'botMatch', fritzTier: 'master', dealSize: 7, trialFormat: 'shortRace', winningScore: 50 },
    completionCriteria: 'Win a short race to 50 vs Master Fritz without hints.',
  },
  {
    id: 'ch1-n12',
    chapterId: JOURNEY_CHAPTER_1_ID,
    chapterTitle: CH1_FRITZ_TRAIL_CHAPTER_TITLE,
    order: 12,
    title: 'The First Grandmaster Trial',
    subtitle: 'Chapter 1 boss—not the end of the Journey.',
    nodeType: 'boss',
    difficulty: 'boss',
    requirements: ['Complete No-Hint Trial'],
    rewardText: 'Fritz Trail Conqueror',
    badgeText: 'BOSS',
    action: { kind: 'botMatch', fritzTier: 'master', dealSize: 7, trialFormat: 'fullMatch', winningScore: 60 },
    completionCriteria: 'Win the first Grandmaster gate at the end of The Fritz Trail.',
  },
];
