import { JOURNEY_CHAPTER_1_ID, type JourneyNode } from '../journeyTypes.ts';

export const CH1_FRITZ_TRAIL_CHAPTER_TITLE = 'Chapter 1: The Fritz Trail';

export const CH1_FRITZ_TRAIL_NODES: JourneyNode[] = [
  {
    id: 'ch1-n01',
    chapterId: JOURNEY_CHAPTER_1_ID,
    chapterTitle: CH1_FRITZ_TRAIL_CHAPTER_TITLE,
    order: 1,
    title: 'Trailhead Briefing',
    subtitle: 'Fritz welcomes you to the long road.',
    nodeType: 'checkpoint',
    difficulty: 'intro',
    requirements: ['Begin the Fritz Trail'],
    rewardText: 'Trail Marker',
    badgeText: 'START',
    action: { kind: 'placeholder' },
    completionCriteria: 'Complete the trailhead briefing.',
  },
  {
    id: 'ch1-n02',
    chapterId: JOURNEY_CHAPTER_1_ID,
    chapterTitle: CH1_FRITZ_TRAIL_CHAPTER_TITLE,
    order: 2,
    title: 'First Score',
    subtitle: 'Win your first short Racehorse push to 25.',
    nodeType: 'match',
    difficulty: 'casual',
    requirements: ['Complete Trailhead Briefing'],
    rewardText: 'First Blood',
    action: { kind: 'botMatch', fritzTier: 'rookie', dealSize: 7, trialFormat: 'shortRace', winningScore: 25 },
    completionCriteria: 'Win a short race to 25 vs Rookie Fritz.',
  },
  {
    id: 'ch1-n03',
    chapterId: JOURNEY_CHAPTER_1_ID,
    chapterTitle: CH1_FRITZ_TRAIL_CHAPTER_TITLE,
    order: 3,
    title: 'Open Ends Trial',
    subtitle: 'Read the board. Maximize open-end pressure.',
    nodeType: 'puzzle',
    difficulty: 'casual',
    requirements: ['Complete First Score'],
    rewardText: 'Open Eye',
    action: { kind: 'puzzle', puzzleId: 'ch1-open-ends' },
    completionCriteria: 'Solve the open-ends challenge puzzle.',
  },
  {
    id: 'ch1-n04',
    chapterId: JOURNEY_CHAPTER_1_ID,
    chapterTitle: CH1_FRITZ_TRAIL_CHAPTER_TITLE,
    order: 4,
    title: 'Draw Escape',
    subtitle: 'Survive the boneyard without panic.',
    nodeType: 'match',
    difficulty: 'casual',
    requirements: ['Complete Open Ends Trial'],
    rewardText: 'Steady Hand',
    action: { kind: 'botMatch', fritzTier: 'rookie', dealSize: 7, trialFormat: 'shortRace', winningScore: 30 },
    completionCriteria: 'Win a short race to 30 vs Rookie Fritz.',
  },
  {
    id: 'ch1-n05',
    chapterId: JOURNEY_CHAPTER_1_ID,
    chapterTitle: CH1_FRITZ_TRAIL_CHAPTER_TITLE,
    order: 5,
    title: 'Quick Reads',
    subtitle: 'Three fast puzzles. One clock. No do-overs.',
    nodeType: 'puzzle',
    difficulty: 'casual',
    requirements: ['Complete Draw Escape'],
    rewardText: 'Fast Eye',
    badgeText: 'SPRINT',
    action: {
      kind: 'puzzleSprint',
      puzzleIds: ['ch1-n05-sprint-1', 'ch1-n05-sprint-2', 'ch1-n05-sprint-3'],
      timeLimitSec: 60,
    },
    completionCriteria: 'Clear the puzzle sprint—three quick reads under one clock.',
  },
  {
    id: 'ch1-n06',
    chapterId: JOURNEY_CHAPTER_1_ID,
    chapterTitle: CH1_FRITZ_TRAIL_CHAPTER_TITLE,
    order: 6,
    title: 'Sharpen Your Eye',
    subtitle: 'Three lessons stand between you and the Grandmaster gate.',
    nodeType: 'checkpoint',
    difficulty: 'standard',
    requirements: ['Complete Quick Reads'],
    rewardText: 'Clear Sight',
    action: { kind: 'placeholder' },
    completionCriteria: 'Complete the checkpoint briefing.',
  },
  {
    id: 'ch1-n07',
    chapterId: JOURNEY_CHAPTER_1_ID,
    chapterTitle: CH1_FRITZ_TRAIL_CHAPTER_TITLE,
    order: 7,
    title: 'Double Trouble',
    subtitle: 'Doubles decide tempo. Know when to feed and when to lock.',
    nodeType: 'checkpoint',
    difficulty: 'standard',
    requirements: ['Complete Tempo Test'],
    rewardText: 'Double Down',
    action: { kind: 'lesson', lessonId: 'doubles-tempo' },
    completionCriteria: 'Complete the doubles checkpoint.',
  },
  {
    id: 'ch1-n08',
    chapterId: JOURNEY_CHAPTER_1_ID,
    chapterTitle: CH1_FRITZ_TRAIL_CHAPTER_TITLE,
    order: 8,
    title: 'Puzzle Gate',
    subtitle: 'One board. One chance. Find the line.',
    nodeType: 'puzzle',
    difficulty: 'standard',
    requirements: ['Complete Double Trouble'],
    rewardText: 'Gate Cleared',
    action: { kind: 'puzzle', puzzleId: 'ch1-puzzle-gate' },
    completionCriteria: 'Solve the puzzle gate challenge.',
  },
  {
    id: 'ch1-n09',
    chapterId: JOURNEY_CHAPTER_1_ID,
    chapterTitle: CH1_FRITZ_TRAIL_CHAPTER_TITLE,
    order: 9,
    title: 'Pressure Hand',
    subtitle: 'Fixed hand under score pressure.',
    nodeType: 'puzzle',
    difficulty: 'hard',
    requirements: ['Complete Puzzle Gate'],
    rewardText: 'Ice Veins',
    action: { kind: 'puzzle', puzzleId: 'ch1-pressure-hand' },
    completionCriteria: 'Clear the pressure-hand challenge.',
  },
  {
    id: 'ch1-n10',
    chapterId: JOURNEY_CHAPTER_1_ID,
    chapterTitle: CH1_FRITZ_TRAIL_CHAPTER_TITLE,
    order: 10,
    title: 'The First Grandmaster Trial',
    subtitle: 'Chapter 1 boss—not the end of the Journey.',
    nodeType: 'boss',
    difficulty: 'boss',
    requirements: ['Complete Pressure Hand'],
    rewardText: 'Fritz Trail Conqueror',
    badgeText: 'BOSS',
    action: { kind: 'botMatch', fritzTier: 'master', dealSize: 7, trialFormat: 'fullMatch', winningScore: 60 },
    completionCriteria: 'Win the first Grandmaster gate at the end of The Fritz Trail.',
  },
];
