import { JOURNEY_CHAPTER_2_ID, type JourneyNode } from '../journeyTypes.ts';

export const CH2_HIGH_LINE_CHAPTER_TITLE = 'Chapter 2: The High Line';

export const CH2_HIGH_LINE_NODES: JourneyNode[] = [
  {
    id: 'ch2-n01',
    chapterId: JOURNEY_CHAPTER_2_ID,
    chapterTitle: CH2_HIGH_LINE_CHAPTER_TITLE,
    order: 1,
    title: 'High Line Briefing',
    subtitle: 'The trail sharpens. Fritz stops offering free ends.',
    nodeType: 'checkpoint',
    difficulty: 'intro',
    requirements: ['Clear The Fritz Trail'],
    rewardText: 'Line Marker',
    badgeText: 'START',
    action: { kind: 'placeholder' },
    completionCriteria: 'Complete the High Line briefing.',
  },
  {
    id: 'ch2-n02',
    chapterId: JOURNEY_CHAPTER_2_ID,
    chapterTitle: CH2_HIGH_LINE_CHAPTER_TITLE,
    order: 2,
    title: 'No Free End',
    subtitle: 'Every open end is a liability on the High Line.',
    nodeType: 'puzzle',
    difficulty: 'standard',
    requirements: ['Complete High Line Briefing'],
    rewardText: 'Closed Lane',
    action: { kind: 'puzzle', puzzleId: 'ch2-no-free-end' },
    completionCriteria: 'Solve the no-free-end challenge.',
  },
  {
    id: 'ch2-n03',
    chapterId: JOURNEY_CHAPTER_2_ID,
    chapterTitle: CH2_HIGH_LINE_CHAPTER_TITLE,
    order: 3,
    title: 'Count Before Contact',
    subtitle: 'Read both ends before you touch the board.',
    nodeType: 'puzzle',
    difficulty: 'standard',
    requirements: ['Complete No Free End'],
    rewardText: 'Cold Read',
    action: { kind: 'puzzle', puzzleId: 'ch2-count-contact' },
    completionCriteria: 'Solve the count-before-contact puzzle.',
  },
  {
    id: 'ch2-n04',
    chapterId: JOURNEY_CHAPTER_2_ID,
    chapterTitle: CH2_HIGH_LINE_CHAPTER_TITLE,
    order: 4,
    title: 'Tight Board',
    subtitle: 'Standard Fritz on a board with no room for charity.',
    nodeType: 'match',
    difficulty: 'standard',
    requirements: ['Complete Count Before Contact'],
    rewardText: 'Tight Grip',
    action: { kind: 'botMatch', fritzTier: 'standard', dealSize: 7, trialFormat: 'shortRace', winningScore: 35 },
    completionCriteria: 'Win a short race to 35 vs Standard Fritz on a tight board.',
  },
  {
    id: 'ch2-n05',
    chapterId: JOURNEY_CHAPTER_2_ID,
    chapterTitle: CH2_HIGH_LINE_CHAPTER_TITLE,
    order: 5,
    title: 'Pressure Exchange',
    subtitle: 'Trade points only when the reply favors you.',
    nodeType: 'puzzle',
    difficulty: 'standard',
    requirements: ['Complete Tight Board'],
    rewardText: 'Even Trade',
    action: { kind: 'puzzle', puzzleId: 'ch2-pressure-exchange' },
    completionCriteria: 'Solve the pressure-exchange challenge.',
  },
  {
    id: 'ch2-n06',
    chapterId: JOURNEY_CHAPTER_2_ID,
    chapterTitle: CH2_HIGH_LINE_CHAPTER_TITLE,
    order: 6,
    title: 'Score Denial Trial',
    subtitle: 'Block Fritz from the line he has been chasing.',
    nodeType: 'match',
    difficulty: 'hard',
    requirements: ['Complete Pressure Exchange'],
    rewardText: 'Denial Crest',
    action: { kind: 'botMatch', fritzTier: 'standard', dealSize: 7, trialFormat: 'shortRace', winningScore: 40 },
    completionCriteria: 'Win a short race to 40 vs Standard Fritz by denying his scoring lane.',
  },
  {
    id: 'ch2-n07',
    chapterId: JOURNEY_CHAPTER_2_ID,
    chapterTitle: CH2_HIGH_LINE_CHAPTER_TITLE,
    order: 7,
    title: 'The Lock',
    subtitle: 'Midpoint briefing—when to seal the board and when to break it.',
    nodeType: 'checkpoint',
    difficulty: 'hard',
    requirements: ['Complete Score Denial Trial'],
    rewardText: 'Lock Key',
    action: { kind: 'placeholder' },
    completionCriteria: 'Complete The Lock checkpoint briefing.',
  },
  {
    id: 'ch2-n08',
    chapterId: JOURNEY_CHAPTER_2_ID,
    chapterTitle: CH2_HIGH_LINE_CHAPTER_TITLE,
    order: 8,
    title: 'Double-Edge Decision',
    subtitle: 'One tile can open two threats. Choose the edge you can survive.',
    nodeType: 'puzzle',
    difficulty: 'hard',
    requirements: ['Complete The Lock'],
    rewardText: 'Edge Sense',
    action: { kind: 'puzzle', puzzleId: 'ch2-double-edge' },
    completionCriteria: 'Solve the double-edge decision puzzle.',
  },
  {
    id: 'ch2-n09',
    chapterId: JOURNEY_CHAPTER_2_ID,
    chapterTitle: CH2_HIGH_LINE_CHAPTER_TITLE,
    order: 9,
    title: 'Low Margin',
    subtitle: 'Elite Fritz with almost no room for a mistake.',
    nodeType: 'match',
    difficulty: 'hard',
    requirements: ['Complete Double-Edge Decision'],
    rewardText: 'Narrow Win',
    action: { kind: 'botMatch', fritzTier: 'elite', dealSize: 7, trialFormat: 'shortRace', winningScore: 45 },
    completionCriteria: 'Win a short race to 45 vs Elite Fritz on low margin.',
  },
  {
    id: 'ch2-n10',
    chapterId: JOURNEY_CHAPTER_2_ID,
    chapterTitle: CH2_HIGH_LINE_CHAPTER_TITLE,
    order: 10,
    title: 'Endgame Gate',
    subtitle: 'Race to 60 with one reply left in the hand.',
    nodeType: 'puzzle',
    difficulty: 'expert',
    requirements: ['Complete Low Margin'],
    rewardText: 'Gate Key',
    action: { kind: 'puzzle', puzzleId: 'ch2-endgame-gate' },
    completionCriteria: 'Clear the endgame gate puzzle.',
  },
  {
    id: 'ch2-n11',
    chapterId: JOURNEY_CHAPTER_2_ID,
    chapterTitle: CH2_HIGH_LINE_CHAPTER_TITLE,
    order: 11,
    title: 'The Squeeze',
    subtitle: 'Master Fritz closes every lane you try to open.',
    nodeType: 'match',
    difficulty: 'expert',
    requirements: ['Complete Endgame Gate'],
    rewardText: 'Iron Tempo',
    action: { kind: 'botMatch', fritzTier: 'master', dealSize: 7, trialFormat: 'shortRace', winningScore: 50 },
    completionCriteria: 'Win a short race to 50 vs Master Fritz under squeeze pressure.',
  },
  {
    id: 'ch2-n12',
    chapterId: JOURNEY_CHAPTER_2_ID,
    chapterTitle: CH2_HIGH_LINE_CHAPTER_TITLE,
    order: 12,
    title: 'High Line Boss',
    subtitle: 'Chapter 2 boss—prove you can hold the line under Master Fritz.',
    nodeType: 'boss',
    difficulty: 'boss',
    requirements: ['Complete The Squeeze'],
    rewardText: 'High Line Crest',
    badgeText: 'BOSS',
    action: { kind: 'botMatch', fritzTier: 'master', dealSize: 7, trialFormat: 'fullMatch', winningScore: 60 },
    completionCriteria: 'Win the High Line boss trial at the end of Chapter 2.',
  },
];
