import { JOURNEY_CHAPTER_3_ID, type JourneyNode } from '../journeyTypes.ts';

export const CH3_LONG_MARCH_CHAPTER_TITLE = 'Chapter 3: The Long March';

export const CH3_LONG_MARCH_NODES: JourneyNode[] = [
  {
    id: 'ch3-n01',
    chapterId: JOURNEY_CHAPTER_3_ID,
    chapterTitle: CH3_LONG_MARCH_CHAPTER_TITLE,
    order: 1,
    title: 'Long March Briefing',
    subtitle: 'Twenty milestones. Endurance beats impulse.',
    nodeType: 'checkpoint',
    difficulty: 'intro',
    requirements: ['Clear The High Line'],
    rewardText: 'March Marker',
    badgeText: 'START',
    action: { kind: 'placeholder' },
    completionCriteria: 'Complete the Long March briefing.',
  },
  {
    id: 'ch3-n02',
    chapterId: JOURNEY_CHAPTER_3_ID,
    chapterTitle: CH3_LONG_MARCH_CHAPTER_TITLE,
    order: 2,
    title: 'Bad Deal Recovery',
    subtitle: 'A weak opening hand is not a lost march.',
    nodeType: 'puzzle',
    difficulty: 'standard',
    requirements: ['Complete Long March Briefing'],
    rewardText: 'Steady Recovery',
    action: { kind: 'puzzle', puzzleId: 'ch3-bad-deal' },
    completionCriteria: 'Solve the bad-deal recovery challenge.',
  },
  {
    id: 'ch3-n03',
    chapterId: JOURNEY_CHAPTER_3_ID,
    chapterTitle: CH3_LONG_MARCH_CHAPTER_TITLE,
    order: 3,
    title: 'Slow Start',
    subtitle: 'Standard Fritz when the race opens quietly.',
    nodeType: 'match',
    difficulty: 'standard',
    requirements: ['Complete Bad Deal Recovery'],
    rewardText: 'Quiet Tempo',
    action: { kind: 'botMatch', fritzTier: 'standard', dealSize: 7, trialFormat: 'shortRace', winningScore: 35 },
    completionCriteria: 'Win a short race to 35 vs Standard Fritz from a slow start.',
  },
  {
    id: 'ch3-n04',
    chapterId: JOURNEY_CHAPTER_3_ID,
    chapterTitle: CH3_LONG_MARCH_CHAPTER_TITLE,
    order: 4,
    title: 'Tempo or Points',
    subtitle: 'Choose the line that wins the hand—not just the turn.',
    nodeType: 'puzzle',
    difficulty: 'standard',
    requirements: ['Complete Slow Start'],
    rewardText: 'Hand Discipline',
    action: { kind: 'puzzle', puzzleId: 'ch3-tempo-points' },
    completionCriteria: 'Solve the tempo-or-points puzzle.',
  },
  {
    id: 'ch3-n05',
    chapterId: JOURNEY_CHAPTER_3_ID,
    chapterTitle: CH3_LONG_MARCH_CHAPTER_TITLE,
    order: 5,
    title: 'No Panic Draw',
    subtitle: 'The boneyard is pressure—not permission to unravel.',
    nodeType: 'puzzle',
    difficulty: 'standard',
    requirements: ['Complete Tempo or Points'],
    rewardText: 'Calm Draw',
    action: { kind: 'puzzle', puzzleId: 'ch3-no-panic-draw' },
    completionCriteria: 'Clear the no-panic draw challenge.',
  },
  {
    id: 'ch3-n06',
    chapterId: JOURNEY_CHAPTER_3_ID,
    chapterTitle: CH3_LONG_MARCH_CHAPTER_TITLE,
    order: 6,
    title: 'Narrow Trail',
    subtitle: 'Standard Fritz on a board with one lane left.',
    nodeType: 'match',
    difficulty: 'standard',
    requirements: ['Complete No Panic Draw'],
    rewardText: 'Narrow Pass',
    action: { kind: 'botMatch', fritzTier: 'standard', dealSize: 7, trialFormat: 'shortRace', winningScore: 40 },
    completionCriteria: 'Win a short race to 40 vs Standard Fritz on a narrow trail.',
  },
  {
    id: 'ch3-n07',
    chapterId: JOURNEY_CHAPTER_3_ID,
    chapterTitle: CH3_LONG_MARCH_CHAPTER_TITLE,
    order: 7,
    title: 'Endurance Rules',
    subtitle: 'Mid-march checkpoint—strategy over multiple hands.',
    nodeType: 'checkpoint',
    difficulty: 'hard',
    requirements: ['Complete Narrow Trail'],
    rewardText: 'Endurance Crest',
    action: { kind: 'placeholder' },
    completionCriteria: 'Complete the Endurance Rules checkpoint.',
  },
  {
    id: 'ch3-n08',
    chapterId: JOURNEY_CHAPTER_3_ID,
    chapterTitle: CH3_LONG_MARCH_CHAPTER_TITLE,
    order: 8,
    title: 'Deny the Swing',
    subtitle: 'Block the line that would flip the race in one hand.',
    nodeType: 'puzzle',
    difficulty: 'hard',
    requirements: ['Complete Endurance Rules'],
    rewardText: 'Swing Denied',
    action: { kind: 'puzzle', puzzleId: 'ch3-deny-swing' },
    completionCriteria: 'Solve the deny-the-swing challenge.',
  },
  {
    id: 'ch3-n09',
    chapterId: JOURNEY_CHAPTER_3_ID,
    chapterTitle: CH3_LONG_MARCH_CHAPTER_TITLE,
    order: 9,
    title: 'Two-Hand Pressure',
    subtitle: 'Elite Fritz across two consecutive scoring hands.',
    nodeType: 'match',
    difficulty: 'hard',
    requirements: ['Complete Deny the Swing'],
    rewardText: 'Pressure Hold',
    action: { kind: 'botMatch', fritzTier: 'elite', dealSize: 7, trialFormat: 'shortRace', winningScore: 45 },
    completionCriteria: 'Win a short race to 45 vs Elite Fritz under two-hand pressure.',
  },
  {
    id: 'ch3-n10',
    chapterId: JOURNEY_CHAPTER_3_ID,
    chapterTitle: CH3_LONG_MARCH_CHAPTER_TITLE,
    order: 10,
    title: 'Pip Count Discipline',
    subtitle: 'Track what remains in the board—not just your hand.',
    nodeType: 'puzzle',
    difficulty: 'hard',
    requirements: ['Complete Two-Hand Pressure'],
    rewardText: 'Pip Ledger',
    action: { kind: 'puzzle', puzzleId: 'ch3-pip-discipline' },
    completionCriteria: 'Clear the pip-count discipline puzzle.',
  },
  {
    id: 'ch3-n11',
    chapterId: JOURNEY_CHAPTER_3_ID,
    chapterTitle: CH3_LONG_MARCH_CHAPTER_TITLE,
    order: 11,
    title: 'Double Trap',
    subtitle: 'Fritz baited a double. Do not spring it for him.',
    nodeType: 'puzzle',
    difficulty: 'hard',
    requirements: ['Complete Pip Count Discipline'],
    rewardText: 'Trap Avoided',
    action: { kind: 'puzzle', puzzleId: 'ch3-double-trap' },
    completionCriteria: 'Solve the double-trap challenge.',
  },
  {
    id: 'ch3-n12',
    chapterId: JOURNEY_CHAPTER_3_ID,
    chapterTitle: CH3_LONG_MARCH_CHAPTER_TITLE,
    order: 12,
    title: 'No Free Turns',
    subtitle: 'Elite Fritz when every pass costs ground.',
    nodeType: 'match',
    difficulty: 'hard',
    requirements: ['Complete Double Trap'],
    rewardText: 'No Charity',
    action: { kind: 'botMatch', fritzTier: 'elite', dealSize: 7, trialFormat: 'shortRace', winningScore: 45 },
    completionCriteria: 'Win a short race to 45 vs Elite Fritz without giving free turns.',
  },
  {
    id: 'ch3-n13',
    chapterId: JOURNEY_CHAPTER_3_ID,
    chapterTitle: CH3_LONG_MARCH_CHAPTER_TITLE,
    order: 13,
    title: 'The Long Hand',
    subtitle: 'Checkpoint—survive the hand that will not end cleanly.',
    nodeType: 'checkpoint',
    difficulty: 'expert',
    requirements: ['Complete No Free Turns'],
    rewardText: 'Long Hand Seal',
    action: { kind: 'placeholder' },
    completionCriteria: 'Complete The Long Hand checkpoint.',
  },
  {
    id: 'ch3-n14',
    chapterId: JOURNEY_CHAPTER_3_ID,
    chapterTitle: CH3_LONG_MARCH_CHAPTER_TITLE,
    order: 14,
    title: 'Race to 50',
    subtitle: 'Mid-match score pressure with the finish still distant.',
    nodeType: 'puzzle',
    difficulty: 'expert',
    requirements: ['Complete The Long Hand'],
    rewardText: 'Midrace Read',
    action: { kind: 'puzzle', puzzleId: 'ch3-race-to-50' },
    completionCriteria: 'Solve the race-to-50 puzzle.',
  },
  {
    id: 'ch3-n15',
    chapterId: JOURNEY_CHAPTER_3_ID,
    chapterTitle: CH3_LONG_MARCH_CHAPTER_TITLE,
    order: 15,
    title: 'Pressure Set I',
    subtitle: 'Master Fritz—first of two late-march trials.',
    nodeType: 'match',
    difficulty: 'expert',
    requirements: ['Complete Race to 50'],
    rewardText: 'Set One Cleared',
    action: { kind: 'botMatch', fritzTier: 'master', dealSize: 7, trialFormat: 'shortRace', winningScore: 50 },
    completionCriteria: 'Win the first Master Fritz pressure set to 50.',
  },
  {
    id: 'ch3-n16',
    chapterId: JOURNEY_CHAPTER_3_ID,
    chapterTitle: CH3_LONG_MARCH_CHAPTER_TITLE,
    order: 16,
    title: 'Save the Five',
    subtitle: 'The 5 end is live. One wrong tile loses the march.',
    nodeType: 'puzzle',
    difficulty: 'expert',
    requirements: ['Complete Pressure Set I'],
    rewardText: 'Five Saved',
    action: { kind: 'puzzle', puzzleId: 'ch3-save-the-five' },
    completionCriteria: 'Clear the save-the-five endgame puzzle.',
  },
  {
    id: 'ch3-n17',
    chapterId: JOURNEY_CHAPTER_3_ID,
    chapterTitle: CH3_LONG_MARCH_CHAPTER_TITLE,
    order: 17,
    title: 'Pressure Set II',
    subtitle: 'Master Fritz again—no margin left for drift.',
    nodeType: 'match',
    difficulty: 'expert',
    requirements: ['Complete Save the Five'],
    rewardText: 'Set Two Cleared',
    action: { kind: 'botMatch', fritzTier: 'master', dealSize: 7, trialFormat: 'fullMatch', winningScore: 60 },
    completionCriteria: 'Win the second full Master Fritz pressure set.',
  },
  {
    id: 'ch3-n18',
    chapterId: JOURNEY_CHAPTER_3_ID,
    chapterTitle: CH3_LONG_MARCH_CHAPTER_TITLE,
    order: 18,
    title: 'Final Gate Briefing',
    subtitle: 'Three nodes from the Long March boss.',
    nodeType: 'checkpoint',
    difficulty: 'expert',
    requirements: ['Complete Pressure Set II'],
    rewardText: 'Gate Brief',
    action: { kind: 'placeholder' },
    completionCriteria: 'Complete the Final Gate briefing.',
  },
  {
    id: 'ch3-n19',
    chapterId: JOURNEY_CHAPTER_3_ID,
    chapterTitle: CH3_LONG_MARCH_CHAPTER_TITLE,
    order: 19,
    title: 'Boss Prep Gate',
    subtitle: 'One puzzle before the Long March boss trial.',
    nodeType: 'puzzle',
    difficulty: 'boss',
    requirements: ['Complete Final Gate Briefing'],
    rewardText: 'Boss Key',
    action: { kind: 'puzzle', puzzleId: 'ch3-boss-prep' },
    completionCriteria: 'Clear the boss prep gate puzzle.',
  },
  {
    id: 'ch3-n20',
    chapterId: JOURNEY_CHAPTER_3_ID,
    chapterTitle: CH3_LONG_MARCH_CHAPTER_TITLE,
    order: 20,
    title: 'Long March Boss',
    subtitle: 'Chapter 3 boss—not the end of Racehorse Journey.',
    nodeType: 'boss',
    difficulty: 'boss',
    requirements: ['Complete Boss Prep Gate'],
    rewardText: 'Long March Seal',
    badgeText: 'BOSS',
    action: { kind: 'botMatch', fritzTier: 'master', dealSize: 7, trialFormat: 'fullMatch', winningScore: 60 },
    completionCriteria: 'Win the Long March boss trial at the end of Chapter 3.',
  },
];
