import { JOURNEY_CHAPTER_4_ID, type JourneyNode } from '../journeyTypes.ts';

export const CH4_PRESSURE_CIRCUIT_CHAPTER_TITLE = 'Chapter 4: The Pressure Circuit';

export const CH4_PRESSURE_CIRCUIT_NODES: JourneyNode[] = [
  {
    id: 'ch4-n01',
    chapterId: JOURNEY_CHAPTER_4_ID,
    chapterTitle: CH4_PRESSURE_CIRCUIT_CHAPTER_TITLE,
    order: 1,
    title: 'Pressure Circuit Briefing',
    subtitle: 'Twenty-four trials. Pressure without panic.',
    nodeType: 'checkpoint',
    difficulty: 'intro',
    requirements: ['Clear The Long March'],
    rewardText: 'Circuit Marker',
    badgeText: 'START',
    action: { kind: 'placeholder' },
    completionCriteria: 'Complete the Pressure Circuit briefing.',
  },
  {
    id: 'ch4-n02',
    chapterId: JOURNEY_CHAPTER_4_ID,
    chapterTitle: CH4_PRESSURE_CIRCUIT_CHAPTER_TITLE,
    order: 2,
    title: 'Hold the Line',
    subtitle: 'Defend a narrow lead without opening a swing lane.',
    nodeType: 'puzzle',
    difficulty: 'standard',
    requirements: ['Complete Pressure Circuit Briefing'],
    rewardText: 'Line Held',
    action: { kind: 'puzzle', puzzleId: 'ch4-hold-line' },
    completionCriteria: 'Solve the hold-the-line challenge.',
  },
  {
    id: 'ch4-n03',
    chapterId: JOURNEY_CHAPTER_4_ID,
    chapterTitle: CH4_PRESSURE_CIRCUIT_CHAPTER_TITLE,
    order: 3,
    title: 'Early Squeeze',
    subtitle: 'Standard Fritz when the board closes early.',
    nodeType: 'match',
    difficulty: 'standard',
    requirements: ['Complete Hold the Line'],
    rewardText: 'Early Grip',
    action: { kind: 'botMatch', fritzTier: 'standard', dealSize: 7, trialFormat: 'shortRace', winningScore: 40 },
    completionCriteria: 'Win a short race to 40 vs Standard Fritz under early squeeze.',
  },
  {
    id: 'ch4-n04',
    chapterId: JOURNEY_CHAPTER_4_ID,
    chapterTitle: CH4_PRESSURE_CIRCUIT_CHAPTER_TITLE,
    order: 4,
    title: 'Take Five or Deny Ten',
    subtitle: 'Small score now—or deny a larger swing later.',
    nodeType: 'puzzle',
    difficulty: 'standard',
    requirements: ['Complete Early Squeeze'],
    rewardText: 'Denial Read',
    action: { kind: 'puzzle', puzzleId: 'ch4-five-or-ten' },
    completionCriteria: 'Solve the take-five-or-deny-ten puzzle.',
  },
  {
    id: 'ch4-n05',
    chapterId: JOURNEY_CHAPTER_4_ID,
    chapterTitle: CH4_PRESSURE_CIRCUIT_CHAPTER_TITLE,
    order: 5,
    title: 'Bad Rack Discipline',
    subtitle: 'A poor rack is not permission to force the board.',
    nodeType: 'puzzle',
    difficulty: 'standard',
    requirements: ['Complete Take Five or Deny Ten'],
    rewardText: 'Rack Control',
    action: { kind: 'puzzle', puzzleId: 'ch4-bad-rack' },
    completionCriteria: 'Clear the bad-rack discipline challenge.',
  },
  {
    id: 'ch4-n06',
    chapterId: JOURNEY_CHAPTER_4_ID,
    chapterTitle: CH4_PRESSURE_CIRCUIT_CHAPTER_TITLE,
    order: 6,
    title: 'No Cheap Ends',
    subtitle: 'Standard Fritz punishes every free end you offer.',
    nodeType: 'match',
    difficulty: 'standard',
    requirements: ['Complete Bad Rack Discipline'],
    rewardText: 'Tight Exit',
    action: { kind: 'botMatch', fritzTier: 'standard', dealSize: 7, trialFormat: 'shortRace', winningScore: 40 },
    completionCriteria: 'Win a short race to 40 vs Standard Fritz without cheap ends.',
  },
  {
    id: 'ch4-n07',
    chapterId: JOURNEY_CHAPTER_4_ID,
    chapterTitle: CH4_PRESSURE_CIRCUIT_CHAPTER_TITLE,
    order: 7,
    title: 'Small Edges',
    subtitle: 'Circuit checkpoint—convert thin advantages into race leads.',
    nodeType: 'checkpoint',
    difficulty: 'hard',
    requirements: ['Complete No Cheap Ends'],
    rewardText: 'Edge Crest',
    action: { kind: 'placeholder' },
    completionCriteria: 'Complete the Small Edges checkpoint.',
  },
  {
    id: 'ch4-n08',
    chapterId: JOURNEY_CHAPTER_4_ID,
    chapterTitle: CH4_PRESSURE_CIRCUIT_CHAPTER_TITLE,
    order: 8,
    title: 'The Safer Score',
    subtitle: 'Two lines score—only one survives Fritz’s reply.',
    nodeType: 'puzzle',
    difficulty: 'hard',
    requirements: ['Complete Small Edges'],
    rewardText: 'Safe Line',
    action: { kind: 'puzzle', puzzleId: 'ch4-safer-score' },
    completionCriteria: 'Solve the safer-score puzzle.',
  },
  {
    id: 'ch4-n09',
    chapterId: JOURNEY_CHAPTER_4_ID,
    chapterTitle: CH4_PRESSURE_CIRCUIT_CHAPTER_TITLE,
    order: 9,
    title: 'Tight Race I',
    subtitle: 'Elite Fritz with the race still close.',
    nodeType: 'match',
    difficulty: 'hard',
    requirements: ['Complete The Safer Score'],
    rewardText: 'Race One',
    action: { kind: 'botMatch', fritzTier: 'elite', dealSize: 7, trialFormat: 'shortRace', winningScore: 45 },
    completionCriteria: 'Win the first Elite Fritz tight-race trial to 45.',
  },
  {
    id: 'ch4-n10',
    chapterId: JOURNEY_CHAPTER_4_ID,
    chapterTitle: CH4_PRESSURE_CIRCUIT_CHAPTER_TITLE,
    order: 10,
    title: 'Break the Chain',
    subtitle: 'Fritz is building tempo hand over hand. Interrupt it.',
    nodeType: 'puzzle',
    difficulty: 'hard',
    requirements: ['Complete Tight Race I'],
    rewardText: 'Chain Broken',
    action: { kind: 'puzzle', puzzleId: 'ch4-break-chain' },
    completionCriteria: 'Solve the break-the-chain challenge.',
  },
  {
    id: 'ch4-n11',
    chapterId: JOURNEY_CHAPTER_4_ID,
    chapterTitle: CH4_PRESSURE_CIRCUIT_CHAPTER_TITLE,
    order: 11,
    title: 'Double Under Fire',
    subtitle: 'A double appears under score pressure—do not feed it blindly.',
    nodeType: 'puzzle',
    difficulty: 'hard',
    requirements: ['Complete Break the Chain'],
    rewardText: 'Fire Discipline',
    action: { kind: 'puzzle', puzzleId: 'ch4-double-fire' },
    completionCriteria: 'Clear the double-under-fire puzzle.',
  },
  {
    id: 'ch4-n12',
    chapterId: JOURNEY_CHAPTER_4_ID,
    chapterTitle: CH4_PRESSURE_CIRCUIT_CHAPTER_TITLE,
    order: 12,
    title: 'Tight Race II',
    subtitle: 'Elite Fritz again—no margin for a loose reply.',
    nodeType: 'match',
    difficulty: 'hard',
    requirements: ['Complete Double Under Fire'],
    rewardText: 'Race Two',
    action: { kind: 'botMatch', fritzTier: 'elite', dealSize: 7, trialFormat: 'shortRace', winningScore: 45 },
    completionCriteria: 'Win the second Elite Fritz tight-race trial to 45.',
  },
  {
    id: 'ch4-n13',
    chapterId: JOURNEY_CHAPTER_4_ID,
    chapterTitle: CH4_PRESSURE_CIRCUIT_CHAPTER_TITLE,
    order: 13,
    title: 'When Behind',
    subtitle: 'Circuit checkpoint—defend from the back without desperation.',
    nodeType: 'checkpoint',
    difficulty: 'expert',
    requirements: ['Complete Tight Race II'],
    rewardText: 'Defender Seal',
    action: { kind: 'placeholder' },
    completionCriteria: 'Complete the When Behind checkpoint.',
  },
  {
    id: 'ch4-n14',
    chapterId: JOURNEY_CHAPTER_4_ID,
    chapterTitle: CH4_PRESSURE_CIRCUIT_CHAPTER_TITLE,
    order: 14,
    title: 'Deny the Comeback',
    subtitle: 'Fritz is closing the gap. Close his lane first.',
    nodeType: 'puzzle',
    difficulty: 'expert',
    requirements: ['Complete When Behind'],
    rewardText: 'Comeback Denied',
    action: { kind: 'puzzle', puzzleId: 'ch4-deny-comeback' },
    completionCriteria: 'Solve the deny-the-comeback challenge.',
  },
  {
    id: 'ch4-n15',
    chapterId: JOURNEY_CHAPTER_4_ID,
    chapterTitle: CH4_PRESSURE_CIRCUIT_CHAPTER_TITLE,
    order: 15,
    title: 'Control Trial',
    subtitle: 'Master Fritz—first control trial of the circuit.',
    nodeType: 'match',
    difficulty: 'expert',
    requirements: ['Complete Deny the Comeback'],
    rewardText: 'Control I',
    action: { kind: 'botMatch', fritzTier: 'master', dealSize: 7, trialFormat: 'shortRace', winningScore: 50 },
    completionCriteria: 'Win the first Master Fritz control trial to 50.',
  },
  {
    id: 'ch4-n16',
    chapterId: JOURNEY_CHAPTER_4_ID,
    chapterTitle: CH4_PRESSURE_CIRCUIT_CHAPTER_TITLE,
    order: 16,
    title: 'Count the Exit',
    subtitle: 'Plan the last three tiles before you touch the board.',
    nodeType: 'puzzle',
    difficulty: 'expert',
    requirements: ['Complete Control Trial'],
    rewardText: 'Exit Count',
    action: { kind: 'puzzle', puzzleId: 'ch4-count-exit' },
    completionCriteria: 'Clear the count-the-exit puzzle.',
  },
  {
    id: 'ch4-n17',
    chapterId: JOURNEY_CHAPTER_4_ID,
    chapterTitle: CH4_PRESSURE_CIRCUIT_CHAPTER_TITLE,
    order: 17,
    title: 'Save Tempo',
    subtitle: 'Pass or play—tempo is the resource you cannot waste.',
    nodeType: 'puzzle',
    difficulty: 'expert',
    requirements: ['Complete Count the Exit'],
    rewardText: 'Tempo Saved',
    action: { kind: 'puzzle', puzzleId: 'ch4-save-tempo' },
    completionCriteria: 'Solve the save-tempo challenge.',
  },
  {
    id: 'ch4-n18',
    chapterId: JOURNEY_CHAPTER_4_ID,
    chapterTitle: CH4_PRESSURE_CIRCUIT_CHAPTER_TITLE,
    order: 18,
    title: 'Control Trial II',
    subtitle: 'Master Fritz again—control the reply, not just the score.',
    nodeType: 'match',
    difficulty: 'expert',
    requirements: ['Complete Save Tempo'],
    rewardText: 'Control II',
    action: { kind: 'botMatch', fritzTier: 'master', dealSize: 7, trialFormat: 'shortRace', winningScore: 50 },
    completionCriteria: 'Win the second Master Fritz control trial to 50.',
  },
  {
    id: 'ch4-n19',
    chapterId: JOURNEY_CHAPTER_4_ID,
    chapterTitle: CH4_PRESSURE_CIRCUIT_CHAPTER_TITLE,
    order: 19,
    title: 'Final Circuit Briefing',
    subtitle: 'Five nodes to the Pressure Circuit boss.',
    nodeType: 'checkpoint',
    difficulty: 'expert',
    requirements: ['Complete Control Trial II'],
    rewardText: 'Final Brief',
    action: { kind: 'placeholder' },
    completionCriteria: 'Complete the Final Circuit briefing.',
  },
  {
    id: 'ch4-n20',
    chapterId: JOURNEY_CHAPTER_4_ID,
    chapterTitle: CH4_PRESSURE_CIRCUIT_CHAPTER_TITLE,
    order: 20,
    title: 'Pressure Gate I',
    subtitle: 'First late-circuit gate—deny before you score.',
    nodeType: 'puzzle',
    difficulty: 'expert',
    requirements: ['Complete Final Circuit Briefing'],
    rewardText: 'Gate One',
    action: { kind: 'puzzle', puzzleId: 'ch4-pressure-gate-1' },
    completionCriteria: 'Clear Pressure Gate I.',
  },
  {
    id: 'ch4-n21',
    chapterId: JOURNEY_CHAPTER_4_ID,
    chapterTitle: CH4_PRESSURE_CIRCUIT_CHAPTER_TITLE,
    order: 21,
    title: 'Final Table',
    subtitle: 'Master Fritz at the circuit final table.',
    nodeType: 'match',
    difficulty: 'expert',
    requirements: ['Complete Pressure Gate I'],
    rewardText: 'Final Table Pass',
    action: { kind: 'botMatch', fritzTier: 'master', dealSize: 7, trialFormat: 'fullMatch', winningScore: 60 },
    completionCriteria: 'Win the full Master Fritz final-table trial.',
  },
  {
    id: 'ch4-n22',
    chapterId: JOURNEY_CHAPTER_4_ID,
    chapterTitle: CH4_PRESSURE_CIRCUIT_CHAPTER_TITLE,
    order: 22,
    title: 'Pressure Gate II',
    subtitle: 'Second gate—one greedy tile loses the circuit.',
    nodeType: 'puzzle',
    difficulty: 'boss',
    requirements: ['Complete Final Table'],
    rewardText: 'Gate Two',
    action: { kind: 'puzzle', puzzleId: 'ch4-pressure-gate-2' },
    completionCriteria: 'Clear Pressure Gate II.',
  },
  {
    id: 'ch4-n23',
    chapterId: JOURNEY_CHAPTER_4_ID,
    chapterTitle: CH4_PRESSURE_CIRCUIT_CHAPTER_TITLE,
    order: 23,
    title: 'No Gifts',
    subtitle: 'Boss prep—Fritz gets nothing for free.',
    nodeType: 'puzzle',
    difficulty: 'boss',
    requirements: ['Complete Pressure Gate II'],
    rewardText: 'No Gifts Seal',
    action: { kind: 'puzzle', puzzleId: 'ch4-boss-prep' },
    completionCriteria: 'Clear the no-gifts boss prep puzzle.',
  },
  {
    id: 'ch4-n24',
    chapterId: JOURNEY_CHAPTER_4_ID,
    chapterTitle: CH4_PRESSURE_CIRCUIT_CHAPTER_TITLE,
    order: 24,
    title: 'Pressure Circuit Boss',
    subtitle: 'Chapter 4 boss—not the end of Racehorse Journey.',
    nodeType: 'boss',
    difficulty: 'boss',
    requirements: ['Complete No Gifts'],
    rewardText: 'Pressure Circuit Crest',
    badgeText: 'BOSS',
    action: { kind: 'botMatch', fritzTier: 'master', dealSize: 7, trialFormat: 'fullMatch', winningScore: 60 },
    completionCriteria: 'Win the Pressure Circuit boss trial at the end of Chapter 4.',
  },
];
