import { JOURNEY_CHAPTER_5_ID, type JourneyNode } from '../journeyTypes.ts';

export const CH5_IRON_MILE_CHAPTER_TITLE = 'Chapter 5: The Iron Mile';

export const CH5_IRON_MILE_NODES: JourneyNode[] = [
  {
    id: 'ch5-n01',
    chapterId: JOURNEY_CHAPTER_5_ID,
    chapterTitle: CH5_IRON_MILE_CHAPTER_TITLE,
    order: 1,
    title: 'Iron Mile Briefing',
    subtitle: 'Twenty-four endgame trials. Close with control.',
    nodeType: 'checkpoint',
    difficulty: 'intro',
    requirements: ['Clear The Pressure Circuit'],
    rewardText: 'Mile Marker',
    badgeText: 'START',
    action: { kind: 'placeholder' },
    completionCriteria: 'Complete the Iron Mile briefing.',
  },
  {
    id: 'ch5-n02',
    chapterId: JOURNEY_CHAPTER_5_ID,
    chapterTitle: CH5_IRON_MILE_CHAPTER_TITLE,
    order: 2,
    title: 'Protect the Lead',
    subtitle: 'Ahead in the race—deny before you score.',
    nodeType: 'puzzle',
    difficulty: 'standard',
    requirements: ['Complete Iron Mile Briefing'],
    rewardText: 'Lead Protected',
    action: { kind: 'puzzle', puzzleId: 'ch5-protect-lead' },
    completionCriteria: 'Solve the protect-the-lead challenge.',
  },
  {
    id: 'ch5-n03',
    chapterId: JOURNEY_CHAPTER_5_ID,
    chapterTitle: CH5_IRON_MILE_CHAPTER_TITLE,
    order: 3,
    title: 'First Mile',
    subtitle: 'Elite Fritz opens the Iron Mile.',
    nodeType: 'match',
    difficulty: 'standard',
    requirements: ['Complete Protect the Lead'],
    rewardText: 'First Mile Pass',
    action: { kind: 'botMatch', fritzTier: 'elite', dealSize: 7, trialFormat: 'shortRace', winningScore: 45 },
    completionCriteria: 'Win the first Elite Fritz Iron Mile trial to 45.',
  },
  {
    id: 'ch5-n04',
    chapterId: JOURNEY_CHAPTER_5_ID,
    chapterTitle: CH5_IRON_MILE_CHAPTER_TITLE,
    order: 4,
    title: 'The Greedy Five',
    subtitle: 'Five points now—or ten Fritz takes on the reply.',
    nodeType: 'puzzle',
    difficulty: 'standard',
    requirements: ['Complete First Mile'],
    rewardText: 'Greedy Denied',
    action: { kind: 'puzzle', puzzleId: 'ch5-greedy-five' },
    completionCriteria: 'Clear the greedy-five puzzle.',
  },
  {
    id: 'ch5-n05',
    chapterId: JOURNEY_CHAPTER_5_ID,
    chapterTitle: CH5_IRON_MILE_CHAPTER_TITLE,
    order: 5,
    title: 'Close the Door',
    subtitle: 'Shut Fritz’s comeback lane before the hand ends.',
    nodeType: 'puzzle',
    difficulty: 'standard',
    requirements: ['Complete The Greedy Five'],
    rewardText: 'Door Closed',
    action: { kind: 'puzzle', puzzleId: 'ch5-close-door' },
    completionCriteria: 'Solve the close-the-door challenge.',
  },
  {
    id: 'ch5-n06',
    chapterId: JOURNEY_CHAPTER_5_ID,
    chapterTitle: CH5_IRON_MILE_CHAPTER_TITLE,
    order: 6,
    title: 'Clean Exit',
    subtitle: 'Elite Fritz—finish the hand without a free end.',
    nodeType: 'match',
    difficulty: 'hard',
    requirements: ['Complete Close the Door'],
    rewardText: 'Clean Exit',
    action: { kind: 'botMatch', fritzTier: 'elite', dealSize: 7, trialFormat: 'shortRace', winningScore: 45 },
    completionCriteria: 'Win the Elite Fritz clean-exit trial to 45.',
  },
  {
    id: 'ch5-n07',
    chapterId: JOURNEY_CHAPTER_5_ID,
    chapterTitle: CH5_IRON_MILE_CHAPTER_TITLE,
    order: 7,
    title: 'Closing Discipline',
    subtitle: 'Checkpoint—convert endgame leads without greed.',
    nodeType: 'checkpoint',
    difficulty: 'hard',
    requirements: ['Complete Clean Exit'],
    rewardText: 'Closeout Crest',
    action: { kind: 'placeholder' },
    completionCriteria: 'Complete the Closing Discipline checkpoint.',
  },
  {
    id: 'ch5-n08',
    chapterId: JOURNEY_CHAPTER_5_ID,
    chapterTitle: CH5_IRON_MILE_CHAPTER_TITLE,
    order: 8,
    title: 'When Ahead, Deny',
    subtitle: 'The race lead is yours—subtraction beats addition.',
    nodeType: 'puzzle',
    difficulty: 'hard',
    requirements: ['Complete Closing Discipline'],
    rewardText: 'Denial Line',
    action: { kind: 'puzzle', puzzleId: 'ch5-when-ahead-deny' },
    completionCriteria: 'Solve the when-ahead-deny puzzle.',
  },
  {
    id: 'ch5-n09',
    chapterId: JOURNEY_CHAPTER_5_ID,
    chapterTitle: CH5_IRON_MILE_CHAPTER_TITLE,
    order: 9,
    title: 'Lead Defense I',
    subtitle: 'Master Fritz—first lead-defense trial.',
    nodeType: 'match',
    difficulty: 'hard',
    requirements: ['Complete When Ahead, Deny'],
    rewardText: 'Defense One',
    action: { kind: 'botMatch', fritzTier: 'master', dealSize: 7, trialFormat: 'shortRace', winningScore: 50 },
    completionCriteria: 'Win the first Master Fritz lead-defense trial to 50.',
  },
  {
    id: 'ch5-n10',
    chapterId: JOURNEY_CHAPTER_5_ID,
    chapterTitle: CH5_IRON_MILE_CHAPTER_TITLE,
    order: 10,
    title: 'The Comeback Trap',
    subtitle: 'Fritz baits a swing—do not feed the comeback.',
    nodeType: 'puzzle',
    difficulty: 'hard',
    requirements: ['Complete Lead Defense I'],
    rewardText: 'Trap Avoided',
    action: { kind: 'puzzle', puzzleId: 'ch5-comeback-trap' },
    completionCriteria: 'Clear the comeback-trap puzzle.',
  },
  {
    id: 'ch5-n11',
    chapterId: JOURNEY_CHAPTER_5_ID,
    chapterTitle: CH5_IRON_MILE_CHAPTER_TITLE,
    order: 11,
    title: 'Pip Count Under Fire',
    subtitle: 'Heavy pips remain—count before you commit.',
    nodeType: 'puzzle',
    difficulty: 'hard',
    requirements: ['Complete The Comeback Trap'],
    rewardText: 'Pip Read',
    action: { kind: 'puzzle', puzzleId: 'ch5-pip-under-fire' },
    completionCriteria: 'Solve the pip-count-under-fire challenge.',
  },
  {
    id: 'ch5-n12',
    chapterId: JOURNEY_CHAPTER_5_ID,
    chapterTitle: CH5_IRON_MILE_CHAPTER_TITLE,
    order: 12,
    title: 'Lead Defense II',
    subtitle: 'Master Fritz again—no margin for a loose reply.',
    nodeType: 'match',
    difficulty: 'hard',
    requirements: ['Complete Pip Count Under Fire'],
    rewardText: 'Defense Two',
    action: { kind: 'botMatch', fritzTier: 'master', dealSize: 7, trialFormat: 'shortRace', winningScore: 50 },
    completionCriteria: 'Win the second Master Fritz lead-defense trial to 50.',
  },
  {
    id: 'ch5-n13',
    chapterId: JOURNEY_CHAPTER_5_ID,
    chapterTitle: CH5_IRON_MILE_CHAPTER_TITLE,
    order: 13,
    title: 'Behind the Count',
    subtitle: 'Checkpoint—recover without hero tiles.',
    nodeType: 'checkpoint',
    difficulty: 'expert',
    requirements: ['Complete Lead Defense II'],
    rewardText: 'Recovery Seal',
    action: { kind: 'placeholder' },
    completionCriteria: 'Complete the Behind the Count checkpoint.',
  },
  {
    id: 'ch5-n14',
    chapterId: JOURNEY_CHAPTER_5_ID,
    chapterTitle: CH5_IRON_MILE_CHAPTER_TITLE,
    order: 14,
    title: 'Take the Small Edge',
    subtitle: 'Two safe points beat five that open Fritz’s lane.',
    nodeType: 'puzzle',
    difficulty: 'expert',
    requirements: ['Complete Behind the Count'],
    rewardText: 'Small Edge',
    action: { kind: 'puzzle', puzzleId: 'ch5-small-edge' },
    completionCriteria: 'Solve the take-the-small-edge puzzle.',
  },
  {
    id: 'ch5-n15',
    chapterId: JOURNEY_CHAPTER_5_ID,
    chapterTitle: CH5_IRON_MILE_CHAPTER_TITLE,
    order: 15,
    title: 'Recovery Trial',
    subtitle: 'Master Fritz—first recovery trial of the mile.',
    nodeType: 'match',
    difficulty: 'expert',
    requirements: ['Complete Take the Small Edge'],
    rewardText: 'Recovery I',
    action: { kind: 'botMatch', fritzTier: 'master', dealSize: 7, trialFormat: 'shortRace', winningScore: 50 },
    completionCriteria: 'Win the first Master Fritz recovery trial to 50.',
  },
  {
    id: 'ch5-n16',
    chapterId: JOURNEY_CHAPTER_5_ID,
    chapterTitle: CH5_IRON_MILE_CHAPTER_TITLE,
    order: 16,
    title: 'Force the Safe Draw',
    subtitle: 'Draw once with discipline—not desperation.',
    nodeType: 'puzzle',
    difficulty: 'expert',
    requirements: ['Complete Recovery Trial'],
    rewardText: 'Safe Draw',
    action: { kind: 'puzzle', puzzleId: 'ch5-safe-draw' },
    completionCriteria: 'Clear the force-the-safe-draw puzzle.',
  },
  {
    id: 'ch5-n17',
    chapterId: JOURNEY_CHAPTER_5_ID,
    chapterTitle: CH5_IRON_MILE_CHAPTER_TITLE,
    order: 17,
    title: 'No Hero Tile',
    subtitle: 'One flashy tile loses the mile—play the boring line.',
    nodeType: 'puzzle',
    difficulty: 'expert',
    requirements: ['Complete Force the Safe Draw'],
    rewardText: 'No Hero',
    action: { kind: 'puzzle', puzzleId: 'ch5-no-hero' },
    completionCriteria: 'Solve the no-hero-tile challenge.',
  },
  {
    id: 'ch5-n18',
    chapterId: JOURNEY_CHAPTER_5_ID,
    chapterTitle: CH5_IRON_MILE_CHAPTER_TITLE,
    order: 18,
    title: 'Recovery Trial II',
    subtitle: 'Master Fritz again—close the gap without gifts.',
    nodeType: 'match',
    difficulty: 'expert',
    requirements: ['Complete No Hero Tile'],
    rewardText: 'Recovery II',
    action: { kind: 'botMatch', fritzTier: 'master', dealSize: 7, trialFormat: 'shortRace', winningScore: 50 },
    completionCriteria: 'Win the second Master Fritz recovery trial to 50.',
  },
  {
    id: 'ch5-n19',
    chapterId: JOURNEY_CHAPTER_5_ID,
    chapterTitle: CH5_IRON_MILE_CHAPTER_TITLE,
    order: 19,
    title: 'Final Mile Briefing',
    subtitle: 'Five nodes to the Iron Mile boss.',
    nodeType: 'checkpoint',
    difficulty: 'expert',
    requirements: ['Complete Recovery Trial II'],
    rewardText: 'Final Brief',
    action: { kind: 'placeholder' },
    completionCriteria: 'Complete the Final Mile briefing.',
  },
  {
    id: 'ch5-n20',
    chapterId: JOURNEY_CHAPTER_5_ID,
    chapterTitle: CH5_IRON_MILE_CHAPTER_TITLE,
    order: 20,
    title: 'Iron Gate I',
    subtitle: 'First late-mile gate—closeout discipline.',
    nodeType: 'puzzle',
    difficulty: 'expert',
    requirements: ['Complete Final Mile Briefing'],
    rewardText: 'Gate One',
    action: { kind: 'puzzle', puzzleId: 'ch5-iron-gate-1' },
    completionCriteria: 'Clear Iron Gate I.',
  },
  {
    id: 'ch5-n21',
    chapterId: JOURNEY_CHAPTER_5_ID,
    chapterTitle: CH5_IRON_MILE_CHAPTER_TITLE,
    order: 21,
    title: 'Closing Table',
    subtitle: 'Master Fritz at the Iron Mile closing table.',
    nodeType: 'match',
    difficulty: 'expert',
    requirements: ['Complete Iron Gate I'],
    rewardText: 'Closing Table Pass',
    action: { kind: 'botMatch', fritzTier: 'master', dealSize: 7, trialFormat: 'fullMatch', winningScore: 60 },
    completionCriteria: 'Win the full Master Fritz closing-table trial.',
  },
  {
    id: 'ch5-n22',
    chapterId: JOURNEY_CHAPTER_5_ID,
    chapterTitle: CH5_IRON_MILE_CHAPTER_TITLE,
    order: 22,
    title: 'Iron Gate II',
    subtitle: 'Second gate—one greedy score loses the mile.',
    nodeType: 'puzzle',
    difficulty: 'boss',
    requirements: ['Complete Closing Table'],
    rewardText: 'Gate Two',
    action: { kind: 'puzzle', puzzleId: 'ch5-iron-gate-2' },
    completionCriteria: 'Clear Iron Gate II.',
  },
  {
    id: 'ch5-n23',
    chapterId: JOURNEY_CHAPTER_5_ID,
    chapterTitle: CH5_IRON_MILE_CHAPTER_TITLE,
    order: 23,
    title: 'Finish Clean',
    subtitle: 'Boss prep—enter the trial with control.',
    nodeType: 'puzzle',
    difficulty: 'boss',
    requirements: ['Complete Iron Gate II'],
    rewardText: 'Clean Finish Seal',
    action: { kind: 'puzzle', puzzleId: 'ch5-boss-prep' },
    completionCriteria: 'Clear the finish-clean boss prep puzzle.',
  },
  {
    id: 'ch5-n24',
    chapterId: JOURNEY_CHAPTER_5_ID,
    chapterTitle: CH5_IRON_MILE_CHAPTER_TITLE,
    order: 24,
    title: 'Iron Mile Boss',
    subtitle: 'Chapter 5 boss—not the end of Racehorse Journey.',
    nodeType: 'boss',
    difficulty: 'boss',
    requirements: ['Complete Finish Clean'],
    rewardText: 'Iron Mile Crest',
    badgeText: 'BOSS',
    action: { kind: 'botMatch', fritzTier: 'master', dealSize: 7, trialFormat: 'fullMatch', winningScore: 60 },
    completionCriteria: 'Win the Iron Mile boss trial at the end of Chapter 5.',
  },
];
