import { JOURNEY_CHAPTER_6_ID, type JourneyNode } from '../journeyTypes.ts';

export const CH6_MASTER_TABLE_CHAPTER_TITLE = 'Chapter 6: The Master Table';

export const CH6_MASTER_TABLE_NODES: JourneyNode[] = [
  {
    id: 'ch6-n01',
    chapterId: JOURNEY_CHAPTER_6_ID,
    chapterTitle: CH6_MASTER_TABLE_CHAPTER_TITLE,
    order: 1,
    title: 'Master Table Briefing',
    subtitle: 'Sixteen seats. Master Fritz only.',
    nodeType: 'checkpoint',
    difficulty: 'intro',
    requirements: ['Clear The Iron Mile'],
    rewardText: 'Table Marker',
    badgeText: 'START',
    action: { kind: 'placeholder' },
    completionCriteria: 'Complete the Master Table briefing.',
  },
  {
    id: 'ch6-n02',
    chapterId: JOURNEY_CHAPTER_6_ID,
    chapterTitle: CH6_MASTER_TABLE_CHAPTER_TITLE,
    order: 2,
    title: 'No Gifts',
    subtitle: 'Fritz gets nothing for free at the table.',
    nodeType: 'puzzle',
    difficulty: 'standard',
    requirements: ['Complete Master Table Briefing'],
    rewardText: 'No Gifts',
    action: { kind: 'puzzle', puzzleId: 'ch6-no-gifts' },
    completionCriteria: 'Solve the no-gifts challenge.',
  },
  {
    id: 'ch6-n03',
    chapterId: JOURNEY_CHAPTER_6_ID,
    chapterTitle: CH6_MASTER_TABLE_CHAPTER_TITLE,
    order: 3,
    title: 'Control Trial',
    subtitle: 'Master Fritz—prove quiet board control at the table.',
    nodeType: 'match',
    difficulty: 'standard',
    requirements: ['Complete No Gifts'],
    rewardText: 'Control Pass',
    action: { kind: 'botMatch', fritzTier: 'master', dealSize: 7, trialFormat: 'shortRace', winningScore: 45 },
    completionCriteria: 'Win the Master Fritz control trial to 45.',
  },
  {
    id: 'ch6-n04',
    chapterId: JOURNEY_CHAPTER_6_ID,
    chapterTitle: CH6_MASTER_TABLE_CHAPTER_TITLE,
    order: 4,
    title: 'Count the Safe Road',
    subtitle: 'Two lines score—only one survives the reply.',
    nodeType: 'puzzle',
    difficulty: 'standard',
    requirements: ['Complete Control Trial'],
    rewardText: 'Safe Road',
    action: { kind: 'puzzle', puzzleId: 'ch6-safe-road' },
    completionCriteria: 'Solve the count-the-safe-road puzzle.',
  },
  {
    id: 'ch6-n05',
    chapterId: JOURNEY_CHAPTER_6_ID,
    chapterTitle: CH6_MASTER_TABLE_CHAPTER_TITLE,
    order: 5,
    title: 'Hold Back the Score',
    subtitle: 'Deny before you score when Master Fritz owns the reply.',
    nodeType: 'puzzle',
    difficulty: 'hard',
    requirements: ['Complete Count the Safe Road'],
    rewardText: 'Score Held',
    action: { kind: 'puzzle', puzzleId: 'ch6-hold-back' },
    completionCriteria: 'Clear the hold-back-the-score challenge.',
  },
  {
    id: 'ch6-n06',
    chapterId: JOURNEY_CHAPTER_6_ID,
    chapterTitle: CH6_MASTER_TABLE_CHAPTER_TITLE,
    order: 6,
    title: 'Closeout Trial',
    subtitle: 'Master Fritz—exit clean without opening a swing lane.',
    nodeType: 'match',
    difficulty: 'hard',
    requirements: ['Complete Hold Back the Score'],
    rewardText: 'Closeout Pass',
    action: { kind: 'botMatch', fritzTier: 'master', dealSize: 7, trialFormat: 'shortRace', winningScore: 45 },
    completionCriteria: 'Win the Master Fritz closeout trial to 45.',
  },
  {
    id: 'ch6-n07',
    chapterId: JOURNEY_CHAPTER_6_ID,
    chapterTitle: CH6_MASTER_TABLE_CHAPTER_TITLE,
    order: 7,
    title: 'Patience Wins',
    subtitle: 'Checkpoint—control beats flash at the table.',
    nodeType: 'checkpoint',
    difficulty: 'hard',
    requirements: ['Complete Closeout Trial'],
    rewardText: 'Patience Crest',
    action: { kind: 'placeholder' },
    completionCriteria: 'Complete the Patience Wins checkpoint.',
  },
  {
    id: 'ch6-n08',
    chapterId: JOURNEY_CHAPTER_6_ID,
    chapterTitle: CH6_MASTER_TABLE_CHAPTER_TITLE,
    order: 8,
    title: 'Quiet Control',
    subtitle: 'No hero tiles—play the line Fritz cannot punish.',
    nodeType: 'puzzle',
    difficulty: 'hard',
    requirements: ['Complete Patience Wins'],
    rewardText: 'Quiet Control',
    action: { kind: 'puzzle', puzzleId: 'ch6-quiet-control' },
    completionCriteria: 'Solve the quiet-control puzzle.',
  },
  {
    id: 'ch6-n09',
    chapterId: JOURNEY_CHAPTER_6_ID,
    chapterTitle: CH6_MASTER_TABLE_CHAPTER_TITLE,
    order: 9,
    title: 'Recovery Trial',
    subtitle: 'Master Fritz—deny the reply when the seat turns.',
    nodeType: 'match',
    difficulty: 'hard',
    requirements: ['Complete Quiet Control'],
    rewardText: 'Recovery Pass',
    action: { kind: 'botMatch', fritzTier: 'master', dealSize: 7, trialFormat: 'shortRace', winningScore: 50 },
    completionCriteria: 'Win the Master Fritz recovery trial to 50.',
  },
  {
    id: 'ch6-n10',
    chapterId: JOURNEY_CHAPTER_6_ID,
    chapterTitle: CH6_MASTER_TABLE_CHAPTER_TITLE,
    order: 10,
    title: 'Trap or Tempo',
    subtitle: 'Fritz baits a swing—or waits for you to waste tempo.',
    nodeType: 'puzzle',
    difficulty: 'expert',
    requirements: ['Complete Recovery Trial'],
    rewardText: 'Tempo Read',
    action: { kind: 'puzzle', puzzleId: 'ch6-trap-tempo' },
    completionCriteria: 'Clear the trap-or-tempo challenge.',
  },
  {
    id: 'ch6-n11',
    chapterId: JOURNEY_CHAPTER_6_ID,
    chapterTitle: CH6_MASTER_TABLE_CHAPTER_TITLE,
    order: 11,
    title: 'The Last Five',
    subtitle: 'Race near 60—plan the final tiles before you play.',
    nodeType: 'puzzle',
    difficulty: 'expert',
    requirements: ['Complete Trap or Tempo'],
    rewardText: 'Five Saved',
    action: { kind: 'puzzle', puzzleId: 'ch6-last-five' },
    completionCriteria: 'Solve the last-five puzzle.',
  },
  {
    id: 'ch6-n12',
    chapterId: JOURNEY_CHAPTER_6_ID,
    chapterTitle: CH6_MASTER_TABLE_CHAPTER_TITLE,
    order: 12,
    title: 'Table Trial',
    subtitle: 'Master Fritz—last disciplined seat before the gate.',
    nodeType: 'match',
    difficulty: 'expert',
    requirements: ['Complete The Last Five'],
    rewardText: 'Table Pass',
    action: { kind: 'botMatch', fritzTier: 'master', dealSize: 7, trialFormat: 'shortRace', winningScore: 50 },
    completionCriteria: 'Win the Master Fritz table trial to 50.',
  },
  {
    id: 'ch6-n13',
    chapterId: JOURNEY_CHAPTER_6_ID,
    chapterTitle: CH6_MASTER_TABLE_CHAPTER_TITLE,
    order: 13,
    title: 'Final Table Briefing',
    subtitle: 'Three nodes to the Master Table boss.',
    nodeType: 'checkpoint',
    difficulty: 'expert',
    requirements: ['Complete Table Trial'],
    rewardText: 'Final Brief',
    action: { kind: 'placeholder' },
    completionCriteria: 'Complete the Final Table briefing.',
  },
  {
    id: 'ch6-n14',
    chapterId: JOURNEY_CHAPTER_6_ID,
    chapterTitle: CH6_MASTER_TABLE_CHAPTER_TITLE,
    order: 14,
    title: 'Clean Hands',
    subtitle: 'Boss gate—enter the final seat with control.',
    nodeType: 'puzzle',
    difficulty: 'boss',
    requirements: ['Complete Final Table Briefing'],
    rewardText: 'Clean Hands',
    action: { kind: 'puzzle', puzzleId: 'ch6-clean-hands' },
    completionCriteria: 'Clear the clean-hands boss gate.',
  },
  {
    id: 'ch6-n15',
    chapterId: JOURNEY_CHAPTER_6_ID,
    chapterTitle: CH6_MASTER_TABLE_CHAPTER_TITLE,
    order: 15,
    title: 'Final Seat',
    subtitle: 'Master Fritz at the closing seat.',
    nodeType: 'match',
    difficulty: 'boss',
    requirements: ['Complete Clean Hands'],
    rewardText: 'Final Seat Pass',
    action: { kind: 'botMatch', fritzTier: 'master', dealSize: 7, trialFormat: 'fullMatch', winningScore: 60 },
    completionCriteria: 'Win the full Master Fritz final-seat trial.',
  },
  {
    id: 'ch6-n16',
    chapterId: JOURNEY_CHAPTER_6_ID,
    chapterTitle: CH6_MASTER_TABLE_CHAPTER_TITLE,
    order: 16,
    title: 'Master Table Boss',
    subtitle: 'Chapter 6 boss—not the end of Racehorse Journey.',
    nodeType: 'boss',
    difficulty: 'boss',
    requirements: ['Complete Final Seat'],
    rewardText: 'Master Table Crest',
    badgeText: 'BOSS',
    action: { kind: 'botMatch', fritzTier: 'master', dealSize: 7, trialFormat: 'fullMatch', winningScore: 60 },
    completionCriteria: 'Win the Master Table boss trial at the end of Chapter 6.',
  },
];
