/**
 * learning/profileProgress.ts
 *
 * Types for the long-term player learning profile and progression system.
 *
 * PHASE 1: Types and interfaces only. No implementation logic.
 *
 * How it fits in:
 *   HandLearningSummary  (handSummary.ts)
 *       ↓  (Phase 6 implementation)
 *   ProfileUpdateInput   ← defined here
 *       ↓
 *   LearningProfile      ← defined here (persisted to storage)
 *       ↓
 *   Progress display / daily goals / lesson suggestions / challenge generation
 */

import type {
  CoachingConceptTag,
  ConceptScoreMap,
  PlayerLevel,
  LearnGameMode,
} from './types';
import type { HandLearningSummary } from './handSummary';

// ---------------------------------------------------------------------------
// Core persistent profile
// ---------------------------------------------------------------------------

/**
 * The full learning profile for one player.
 * Persisted between sessions (localStorage or server-side, TBD).
 *
 * Concept scores are 0–100:
 *   0   = no data yet
 *   1–39 = developing
 *   40–69 = competent
 *   70–89 = strong
 *   90–100 = expert
 */
export type LearningProfile = {
  /** ISO 8601 timestamp of profile creation */
  createdAt: string;

  /** ISO 8601 timestamp of last update */
  updatedAt: string;

  // --- Volume counters ---
  gamesPlayed: number;
  handsPlayed: number;
  moveCount: number;

  /**
   * Running average move accuracy across all hands (0–1).
   * Updated incrementally; never recomputed from scratch.
   */
  averageAccuracy: number;

  /** Per-concept mastery scores (0–100) */
  conceptScores: ConceptScoreMap;

  /**
   * Concept tags the player repeatedly struggles with.
   * Populated when a concept appears in weakestConcept for 2+ consecutive hands.
   */
  recurringMistakeTags: CoachingConceptTag[];

  /**
   * Last N key lessons the player was shown (most recent first).
   * Used to avoid showing the same lesson twice in a row.
   */
  recentLessons: string[];

  /** Streak counters */
  streaks: PlayerStreaks;

  /**
   * The learning mode the player uses most.
   * May influence which features to surface.
   */
  preferredMode: LearnGameMode;

  /**
   * Computed skill level based on conceptScores average.
   * Used to calibrate coaching depth and copy vocabulary.
   */
  computedLevel: PlayerLevel;
};

// ---------------------------------------------------------------------------
// Streak tracking
// ---------------------------------------------------------------------------

export type PlayerStreaks = {
  /** Number of consecutive days the player has played at least one hand */
  daysPlayed: number;

  /** Number of consecutive hands with zero blunders */
  handsWithNoBlunder: number;

  /** Number of consecutive hands where move accuracy ≥ 0.8 */
  strongScoringHands: number;
};

// ---------------------------------------------------------------------------
// Profile update input (produced at end of each hand)
// ---------------------------------------------------------------------------

/**
 * The data the profile updater needs after each hand.
 * Keeps Phase 6 functions pure: they take this in, return a new profile.
 */
export type ProfileUpdateInput = {
  /** Summary of the completed hand */
  handSummary: HandLearningSummary;

  /** The game mode the hand was played in */
  gameMode: LearnGameMode;

  /** ISO 8601 date string for the session (used for streak calculation) */
  sessionDate: string;
};

// ---------------------------------------------------------------------------
// Concept score update record
// ---------------------------------------------------------------------------

/**
 * How a single concept score should change after a hand.
 * Generated by the Phase 6 updater; stored in a delta log for debugging.
 */
export type ConceptScoreDelta = {
  concept: CoachingConceptTag;
  previousScore: number;
  newScore: number;
  delta: number;
  reason: 'improved' | 'declined' | 'no_data_this_hand';
};

// ---------------------------------------------------------------------------
// Computed profile summary — lightweight view for UI widgets
// ---------------------------------------------------------------------------

/**
 * A slimmed-down view of the profile for use in progress bars, header
 * widgets, and daily goal displays. Does NOT expose raw internals.
 */
export type ProfileSummaryView = {
  computedLevel: PlayerLevel;
  averageAccuracy: number;         // 0–1
  overallMasteryScore: number;     // 0–100, average of all conceptScores
  strongestConcept: CoachingConceptTag;
  weakestConcept: CoachingConceptTag;
  streaks: PlayerStreaks;
  handsPlayed: number;
  recentLesson: string | null;     // most recent lesson string, or null
};

// ---------------------------------------------------------------------------
// Daily goal shape (Phase 6+ feature, architecture ready now)
// ---------------------------------------------------------------------------

/**
 * A single daily learning goal surfaced to the player.
 * Generated from recurringMistakeTags and weakestConcept.
 */
export type DailyLearningGoal = {
  concept: CoachingConceptTag;

  /** Short prompt, e.g. "Focus on safer opening moves today" */
  promptText: string;

  /**
   * Target number of hands to complete with no mistakes in this concept.
   * Start small (2–3); increase as player improves.
   */
  targetHandCount: number;

  /** How many qualifying hands completed so far today */
  handsCompleted: number;

  /** True when the player has hit the targetHandCount */
  isComplete: boolean;
};

// ---------------------------------------------------------------------------
// Storage contract — decouples profile logic from persistence mechanism
// ---------------------------------------------------------------------------

/**
 * The interface the Phase 6 persistence layer must implement.
 * Keeps the profile update logic agnostic to whether storage is
 * localStorage, IndexedDB, Supabase, etc.
 */
export interface LearningProfileStore {
  /** Load the current player's profile (or null if none exists) */
  load(): Promise<LearningProfile | null>;

  /** Persist a full profile */
  save(profile: LearningProfile): Promise<void>;

  /** Reset the profile to a fresh state (used for testing / new players) */
  reset(): Promise<void>;
}
