import type { CreateBotMatchViewModelArgs } from './createBotMatchViewModelArgs.ts';
import { buildHandRevealTileReveals } from './buildHandRevealTileReveals.ts';
import type { BotMatchScreenViewModel } from './botMatchViewModelTypes.ts';

export function assembleBotMatchViewModel(args: CreateBotMatchViewModelArgs): BotMatchScreenViewModel {
  const {
    props,
    guidedBoot,
    bootstrap,
    refs,
    chrome,
    authoring,
    presentation,
    ghost,
    dailyFritz,
    review,
    turns,
    rating,
    puzzle,
    navigation,
  } = args;

  const {
    onBack,
    onNavigate,
    currentGlickoRating = null,
    dailyFritzSetOverlay = null,
    onDailyFritzGameComplete = null,
    onProfileRefresh = null,
  } = props;

  const {
    isGuidedMode,
    isAuthoringMode,
    isAuthoringV2Mode,
    isGuidedV2Mode,
    guidedV2BootError,
    frozenLesson,
    guidedInitSourceRef,
  } = guidedBoot;

  const {
    match,
    mode,
    winningScore,
    dealSize,
    opponentLabel,
    userId,
    selectedTile,
    setSelectedTile,
    setSelectedController,
    showRecommendation,
    setShowRecommendation,
    isGhostMode,
    isDailyFritzMode,
    isJourneyTrial,
    isDailyPuzzleRun,
    isStandaloneFritzMatch,
    isPlayVsFritzGameOver,
    showPostGameOverlays,
    enableGuidedMatchCandidateCapture,
    preGameDrawActive,
  } = bootstrap;

  const navigationVm = {
    onBack,
    onNavigate,
    exitMatch: navigation.exitMatch,
    exitJourneyTrial: navigation.exitJourneyTrial,
    goHome: navigation.goHome,
    returnToFritzSetup: navigation.returnToFritzSetup,
    returnToLearn: navigation.returnToLearn,
    startFreshMatch: navigation.startFreshMatch,
    onProfileRefresh,
    onDailyFritzGameComplete,
  };

  const layout = {
    mode,
    winningScore,
    dealSize,
    isDailyFritzMode,
    dailyFritzBoardHasPlay: presentation.dailyFritzBoardHasPlay,
    isLessonLayoutMode: turns.isLessonLayoutMode,
    isGhostMode,
    isGuidedMode,
    isAuthoringMode,
    isAuthoringV2Mode,
    isGuidedV2Mode,
    isJourneyTrial,
    isDailyPuzzleRun,
    isStandaloneFritzMatch,
    isPlayVsFritzGameOver,
    guidedV2BootError,
    enableGuidedMatchCandidateCapture,
    enableDailyFritzProfiling: presentation.enableDailyFritzProfiling,
    userId: userId ?? null,
    currentGlickoRating,
    matchStartGlickoRating: ghost.matchStartGlickoRating,
    rootRef: refs.rootRef,
    boardStageRef: refs.boardStageRef,
    isTransitioningRef: refs.isTransitioningRef,
    isFullscreen: chrome.isFullscreen,
    isMuted: chrome.isMuted,
    setIsMuted: chrome.setIsMuted,
    toggleFullscreen: presentation.toggleFullscreen,
    scoreTrackOpen: chrome.scoreTrackOpen,
    setScoreTrackOpen: chrome.setScoreTrackOpen,
    showLeaveConfirm: chrome.showLeaveConfirm,
    setShowLeaveConfirm: chrome.setShowLeaveConfirm,
  };

  const preGameDraw = {
    drawState: dailyFritz.preGameDraw.drawState,
    isPlayerPickEnabled: dailyFritz.preGameDraw.isPlayerPickEnabled,
    isOpponentThinking: dailyFritz.preGameDraw.isOpponentThinking,
    resultMessage: dailyFritz.preGameDraw.resultMessage,
    handlePlayerTileTap: dailyFritz.preGameDraw.handlePlayerTileTap,
  };

  const hud = {
    opponentLabel,
    ghostSubLabel: ghost.ghostSubLabel,
    botTurn: presentation.botTurn,
    handActive: presentation.handActive,
    handReveal: turns.handReveal,
    preGameDrawActive,
    preGameDraw,
    dailyFritzPackage: bootstrap.dailyFritzPackage,
    opponentPillRef: refs.opponentPillRef,
    drawStepBotHandCount: turns.drawStepBotHandCount,
    fritzPresentation: turns.fritzPresentation ?? null,
  };

  const board = {
    boardRef: refs.boardRef,
    boneyardRef: refs.boneyardRef,
    ghostBoardPulse: ghost.ghostBoardPulse,
    openEnds: presentation.openEnds,
    openEndsSum: presentation.openEndsSum,
    scoreToast: presentation.scoreToast,
    lastPlayedTile: presentation.lastPlayedTile,
    selectedTile,
    onPositionClick: turns.onPositionClick,
    activePlacementMoves: turns.activePlacementMoves,
    lessonBoardPlacementMoves: turns.lessonBoardPlacementMoves,
    isGhostMode,
    ghostAgreementType: ghost.ghostAgreementType,
    ghostPlayedTile: ghost.ghostPlayedTile,
    isJourneyTrial,
    guidedMatchCaptureStatus: turns.guidedMatchCaptureStatus,
    copyGuidedMatchCandidate: turns.copyGuidedMatchCandidate,
    enableGuidedMatchCandidateCapture,
  };

  const hand = {
    handAreaRef: refs.handAreaRef,
    handTileSize: presentation.handTileSize,
    lessonHandRowCount: presentation.lessonHandRowCount,
    selectedTile,
    setSelectedTile,
    setSelectedController,
    handActive: presentation.handActive,
    botTurn: presentation.botTurn,
    drawSequenceActive: turns.drawSequenceActive,
    drawPulseIndex: turns.drawPulseIndex,
    playableTileKeys: presentation.playableTileKeys,
    isGuidedMode,
    isDailyFritzMode,
    preGameDrawActive,
    guidedScoringTiles: turns.guidedScoringTiles,
    showCoachedRecommendation: turns.showCoachedRecommendation,
    lessonRecommendedTileKey: turns.lessonRecommendedTileKey,
  };

  const coach = {
    coach: turns.coach,
    guidedScoringTiles: turns.guidedScoringTiles,
    showCoachedRecommendation: turns.showCoachedRecommendation,
    lessonRecommendedTileKey: turns.lessonRecommendedTileKey,
    playBestMove: turns.playBestMove,
    guidedCoachTip: turns.guidedCoachTip,
    frozenLesson,
    showPlayerCoaching: turns.showPlayerCoaching,
    lessonCoachVm: turns.lessonCoachVm,
    lessonCoachContent: turns.lessonCoachContent,
    showFritzCoachingPanel: turns.showFritzCoachingPanel,
    showLessonCoachPanel: turns.showLessonCoachPanel,
    lessonCoachPanelContent: turns.lessonCoachPanelContent,
    lessonCoachProgressLabel: turns.lessonCoachProgressLabel,
    lessonCoachProgressPct: turns.lessonCoachProgressPct,
    canPlayCoachedMove: turns.canPlayCoachedMove,
    playLessonBestMove: turns.playLessonBestMove,
    isGuidedMatchVictoryResult: turns.isGuidedMatchVictoryResult,
    guidedMatchFinalDebrief: turns.guidedMatchFinalDebrief,
    guidedMatchCaptureStatus: turns.guidedMatchCaptureStatus,
    guidedMatchCandidateSaveStatus: turns.guidedMatchCandidateSaveStatus,
    copyGuidedMatchCandidate: turns.copyGuidedMatchCandidate,
    saveGuidedMatchCandidate: turns.saveGuidedMatchCandidate,
    canSaveGuidedMatchCandidate: turns.canSaveGuidedMatchCandidate,
    authoringSteps: authoring.authoringSteps,
    authoringNoteText: authoring.authoringNoteText,
    setAuthoringNoteText: authoring.setAuthoringNoteText,
    saveAuthoringNoteOnly: authoring.saveAuthoringNoteOnly,
    authoringV2PlayerMoveIndex: turns.authoringV2PlayerMoveIndex,
    isAuthoringMode,
    isAuthoringV2Mode,
    isGuidedMode,
    showFullCoachTip: chrome.showFullCoachTip,
    setShowFullCoachTip: chrome.setShowFullCoachTip,
    showRecommendation,
    setShowRecommendation,
    guidedFritzAnchorRef: refs.guidedFritzAnchorRef,
    guidedBoneyardAnchorRef: refs.guidedBoneyardAnchorRef,
  };

  const debug = {
    showDebug: presentation.showDebug,
    getDebugSnapshot: turns.getDebugSnapshot,
    guidedInitSourceRef,
    lastDailyFlowLabelRef: refs.lastDailyFlowLabelRef,
    dailyFritzSubmitSucceededRef: dailyFritz.dailyFritzSubmitSucceededRef,
    lastBotChoice: turns.lastBotChoice,
  };

  const handRevealTileReveals = buildHandRevealTileReveals(turns.handReveal, opponentLabel);

  const overlays = {
    modals: {
      scoreTrackOpen: chrome.scoreTrackOpen,
      setScoreTrackOpen: chrome.setScoreTrackOpen,
      winningScore,
      opponentLabel,
      handReveal: turns.handReveal,
      handRevealProgress: turns.handRevealProgress,
      handAdvanceError: turns.handAdvanceError,
      showManualHandAdvance: turns.showManualHandAdvance,
      ghostResultError: ghost.ghostResultError,
      setGhostResultError: ghost.setGhostResultError,
      isGuidedMode,
      isGuidedV2Mode,
      isDailyFritzMode,
      handRevealTileReveals,
      coach: turns.coach,
      advanceHand: turns.advanceHand,
      retryHandAdvance: turns.retryHandAdvance,
      dailyFritzSetOverlay,
      shareCopied: dailyFritz.shareCopied,
      handleShareResult: dailyFritz.handleShareResult,
      showPostGameOverlays,
      pivotalReviewOpen: review.pivotalReviewOpen,
      pivotalSelection: review.pivotalSelection,
      completePivotalTurnReview: review.completePivotalTurnReview,
      pivotalReviewSummary: review.pivotalReviewSummary,
      postGameAnalysis: review.postGameAnalysis,
      showPostGameReviewPrompt: review.showPostGameReviewPrompt,
      savePivotalReviewSummary: review.savePivotalReviewSummary,
      openHandScopedReview: review.openHandScopedReview,
      openReviewGameFromPrompt: review.openReviewGameFromPrompt,
      skipPostGameReview: review.skipPostGameReview,
      showPlayVsFritzResultOverlay: review.showPlayVsFritzResultOverlay,
      isJourneyTrial,
      ghostResultLoading: ghost.ghostResultLoading,
      hasConfirmedFritzRatingUpdate: rating.hasConfirmedFritzRatingUpdate,
      fritzNewGlickoRating: rating.fritzNewGlickoRating,
      showFritzRatingSyncing: rating.showFritzRatingSyncing,
      currentGlickoRating,
      matchStartGlickoRating: ghost.matchStartGlickoRating,
      fritzGlickoDelta: rating.fritzGlickoDelta,
      ghostResult: ghost.ghostResult,
      botPostGameReviewEligible: review.botPostGameReviewEligible,
      postGameAnalysisPending: review.postGameAnalysisPending,
      isPlayVsFritzGameOver,
      isGuidedMatchVictoryResult: turns.isGuidedMatchVictoryResult,
      isGhostMode,
      ghostSubLabel: ghost.ghostSubLabel,
      guidedMatchFinalDebrief: turns.guidedMatchFinalDebrief,
      enableGuidedMatchCandidateCapture,
      guidedMatchCaptureStatus: turns.guidedMatchCaptureStatus,
      guidedMatchCandidateSaveStatus: turns.guidedMatchCandidateSaveStatus,
      dailyFritzRank: dailyFritz.dailyFritzRank,
      dailyFritzLeaderboard: dailyFritz.dailyFritzLeaderboard,
      isDailyPuzzleRun,
      userId: userId ?? null,
      dailyLeaderboardLoading: puzzle.dailyLeaderboardLoading,
      dailyLeaderboardError: puzzle.dailyLeaderboardError,
      dailyLeaderboard: puzzle.dailyLeaderboard,
      ghostRatingDeltaLabel: ghost.ghostRatingDeltaLabel,
      ghostResultMessage: ghost.ghostResultMessage,
      canSaveGuidedMatchCandidate: turns.canSaveGuidedMatchCandidate,
      copyGuidedMatchCandidate: turns.copyGuidedMatchCandidate,
      saveGuidedMatchCandidate: turns.saveGuidedMatchCandidate,
      retryDailyFritzCompletion: dailyFritz.retryDailyFritzCompletion,
      reopenPostGameReview: review.reopenPostGameReview,
      navigation: navigationVm,
    },
    inGame: {
      flyingTiles: turns.flyingTiles,
      isLessonLayoutMode: turns.isLessonLayoutMode,
      showFullCoachTip: chrome.showFullCoachTip,
      showPlayerCoaching: turns.showPlayerCoaching,
      lessonCoachVm: turns.lessonCoachVm,
      lessonCoachContent: turns.lessonCoachContent,
      setShowFullCoachTip: chrome.setShowFullCoachTip,
      analyzerOpen: review.analyzerOpen,
      closeAnalyzer: review.closeAnalyzer,
      currentAnalysis: review.currentAnalysis,
      reviewerScopeHandNumber: review.reviewerScopeHandNumber,
      reviewerInitialMoveIndex: review.reviewerInitialMoveIndex,
      opponentLabel,
      showDebug: presentation.showDebug,
      botHand: match.players.bot.hand.map((t) => `[${t.low}|${t.high}]`).join(' '),
      openEnds: presentation.openEnds,
      lastBotChoice: turns.lastBotChoice,
      showLeaveConfirm: chrome.showLeaveConfirm,
      setShowLeaveConfirm: chrome.setShowLeaveConfirm,
      isJourneyTrial,
      isStandaloneFritzMatch,
      matchGameOver: match.gameOver,
      navigation: {
        exitJourneyTrial: navigation.exitJourneyTrial,
        exitMatch: navigation.exitMatch,
        onProfileRefresh,
      },
      abandonStandaloneFritzMatch: rating.abandonStandaloneFritzMatch,
    },
  };

  return {
    match,
    navigation: navigationVm,
    layout,
    hud,
    board,
    hand,
    coach,
    overlays,
    debug,
  };
}
